# Generated by Django 3.2.19 on 2023-06-17 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauDossierSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fichier', models.FileField(blank=True, default=None, null=True, upload_to='dossiers_sinistres/bordereaux')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('ATTENTE', 'Attente'), ('PAYE', 'Paye'), ('ANNULER', 'Annuler')], default='ATTENTE', max_length=15, null=True)),
                ('net_a_payer', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('prestataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire')),
            ],
            options={
                'verbose_name': 'Bordereau prise en charge',
                'verbose_name_plural': 'Bordereaux prises en charge',
                'db_table': 'bordereaux_dossiers_sinistres',
            },
        ),
        migrations.CreateModel(
            name='DossierSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renseignement_clinique', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=25)),
                ('libelle', models.CharField(max_length=100)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.affection')),
                ('aliment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.aliment')),
                ('compagnie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('formulegarantie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.formulegarantie')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
                ('prescripteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.prescripteur')),
                ('prestataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire')),
                ('type_priseencharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typepriseencharge')),
            ],
            options={
                'verbose_name': 'Prise en charges',
                'verbose_name_plural': 'Prises en charge',
                'db_table': 'dossier_sinistre',
            },
        ),
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('type_sinistre', models.CharField(max_length=100, null=True)),
                ('prix_unitaire', models.IntegerField(default=0)),
                ('frais_reel', models.FloatField(null=True)),
                ('ticket_moderateur', models.FloatField(null=True)),
                ('depassement', models.FloatField(null=True)),
                ('nombre_demande', models.IntegerField(null=True)),
                ('nombre_accorde', models.IntegerField(null=True)),
                ('plafond_chambre', models.FloatField(null=True)),
                ('plafond_hospit', models.FloatField(null=True)),
                ('montant_plafond', models.FloatField(null=True)),
                ('nombre_plafond', models.IntegerField(null=True)),
                ('nature', models.IntegerField(null=True)),
                ('frequence', models.IntegerField(null=True)),
                ('unite_frequence', models.FloatField(null=True)),
                ('franchise_min', models.FloatField(null=True)),
                ('franchise_max', models.FloatField(null=True)),
                ('delai_controle', models.IntegerField(null=True)),
                ('part_assure', models.FloatField(null=True)),
                ('part_compagnie', models.FloatField(null=True)),
                ('date_survenance', models.DateTimeField(null=True)),
                ('date_entree', models.DateTimeField(null=True)),
                ('date_sortie', models.DateTimeField(null=True)),
                ('motif_rejet', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete')], default='EN ATTENTE', max_length=15, null=True)),
                ('statut_prestation', models.CharField(choices=[('EFFECTUE', 'Effectue'), ('NON EFFECTUE', 'Attente')], default='EFFECTUE', max_length=15, null=True)),
                ('statut_bordereau', models.CharField(choices=[('AJOUTE BORDEREAU', 'Ajoute Bordereau'), ('PAYE', 'Paye'), ('ATTENTE DE PAIEMENT', 'Attente')], default='ATTENTE DE PAIEMENT', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.acte')),
                ('adherent_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='famille', to='production.aliment')),
                ('affection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.affection')),
                ('aliment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.aliment')),
                ('approuved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approbateur', to=settings.AUTH_USER_MODEL)),
                ('compagnie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('dossier_sinistre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sinistres', to='sinistre.dossiersinistre')),
                ('medicament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.medicament')),
                ('periode_couverture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.periodecouverture')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
                ('prescripteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.prescripteur')),
                ('prestataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire')),
            ],
            options={
                'verbose_name': 'Sinistre',
                'verbose_name_plural': 'Sinistres',
                'db_table': 'sinistres',
            },
        ),
        migrations.CreateModel(
            name='DocumentDossierSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('fichier', models.FileField(blank=True, default=None, null=True, upload_to='dossiers_sinistres/documents')),
                ('commentaire', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier_sinistre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='sinistre.dossiersinistre')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.typedocument')),
            ],
            options={
                'verbose_name': 'Document prise en charge',
                'verbose_name_plural': 'Documents prises en charge',
                'db_table': 'documents_dossiers_sinistres',
            },
        ),
        migrations.CreateModel(
            name='BordereauSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bordereau', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sinistres', to='sinistre.bordereaudossiersinistre')),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
            ],
            options={
                'verbose_name': 'Bordereau sinistre',
                'verbose_name_plural': 'Bordereaux sinistres',
                'db_table': 'bordereaux_sinistres',
            },
        ),
    ]
