# Generated by Django 3.2.15 on 2023-06-23 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0003_dossiersinistre_centre_prescripteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='served_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='serveur', to=settings.AUTH_USER_MODEL),
        ),
    ]
