# Generated by Django 3.2.19 on 2023-06-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0005_auto_20230625_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiersinistre',
            name='plafond_chambre',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dossiersinistre',
            name='plafond_hospit',
            field=models.FloatField(null=True),
        ),
    ]
