# Generated by Django 3.2.19 on 2023-06-26 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0006_auto_20230626_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiersinistre',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
