# Generated by Django 3.2.19 on 2023-06-28 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0007_dossiersinistre_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='updated_price_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_price_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
