# Generated by Django 3.2.19 on 2023-06-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0008_sinistre_updated_price_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProrogationSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_jour', models.CharField(blank=True, max_length=255, null=True)),
                ('date_entree', models.DateTimeField(null=True)),
                ('date_sortie', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
            ],
            options={
                'verbose_name': 'Prorogation',
                'verbose_name_plural': 'Prorogations',
                'db_table': 'prorogation_sinistre',
            },
        ),
    ]
