# Generated by Django 3.2.19 on 2023-07-02 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0010_prorogationsinistre_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='prorogationsinistre',
            name='statut',
            field=models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete')], default='EN ATTENTE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prorogationsinistre',
            name='sinistre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prorogations', to='sinistre.sinistre'),
        ),
    ]
