# Generated by Django 3.2.19 on 2023-07-03 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0011_auto_20230702_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prorogationsinistre',
            old_name='motif',
            new_name='motif_demande',
        ),
        migrations.RenameField(
            model_name='prorogationsinistre',
            old_name='nombre_jour',
            new_name='motif_rejet',
        ),
        migrations.AddField(
            model_name='prorogationsinistre',
            name='jour_accorde',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prorogationsinistre',
            name='jour_demande',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prorogationsinistre',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
