# Generated by Django 3.2.19 on 2023-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0013_auto_20230718_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='prix_unitaire',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
