# Generated by Django 3.2.15 on 2023-07-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0017_auto_20230719_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossiersinistre',
            options={'verbose_name': 'Prise en charges', 'verbose_name_plural': 'Liste des prises en charge'},
        ),
    ]
