# Generated by Django 3.2.15 on 2023-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0018_alter_dossiersinistre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='statut',
            field=models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete')], default='ACCORDE', max_length=15, null=True),
        ),
    ]
