# Generated by Django 3.2.15 on 2023-09-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0019_alter_sinistre_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='statut_synchro_veos',
            field=models.BooleanField(default=False),
        ),
    ]
