# Generated by Django 3.2.15 on 2023-09-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0020_sinistre_statut_synchro_veos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='reviewed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
