# Generated by Django 3.2.15 on 2023-09-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0056_auto_20230912_1754'),
        ('production', '0026_auto_20230911_1623'),
        ('sinistre', '0021_sinistre_reviewed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlePlafond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('plafond_conso_famille', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('plafond_conso_individuel', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('plafond_conso_sous_rubrique', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('plafond_conso_regroupement_acte', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('plafond_conso_acte', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.acte')),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.aliment')),
                ('regroupement_acte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.regroupementacte')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.rubrique')),
                ('sous_rubrique', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.sousrubrique')),
            ],
            options={
                'verbose_name': 'Controle plafond',
                'verbose_name_plural': 'Controle plafonds',
                'db_table': 'controle_plafond',
            },
        ),
    ]
