# Generated by Django 3.2.15 on 2023-09-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0022_controleplafond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controleplafond',
            old_name='session',
            new_name='session_pec',
        ),
    ]
