# Generated by Django 3.2.15 on 2023-09-27 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0056_auto_20230912_1754'),
        ('production', '0026_auto_20230911_1623'),
        ('sinistre', '0023_rename_session_controleplafond_session_pec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleplafond',
            name='acte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.acte'),
        ),
        migrations.AlterField(
            model_name='controleplafond',
            name='aliment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.aliment'),
        ),
        migrations.AlterField(
            model_name='controleplafond',
            name='regroupement_acte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.regroupementacte'),
        ),
        migrations.AlterField(
            model_name='controleplafond',
            name='sous_rubrique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.sousrubrique'),
        ),
    ]
