# Generated by Django 3.2.15 on 2023-09-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0024_auto_20230927_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controleplafond',
            name='plafond_conso_acte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controleplafond',
            name='plafond_conso_famille',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controleplafond',
            name='plafond_conso_individuel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controleplafond',
            name='plafond_conso_regroupement_acte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controleplafond',
            name='plafond_conso_sous_rubrique',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='controleplafond',
            name='session_pec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
