# Generated by Django 3.2.15 on 2023-09-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0026_sinistretemporaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistretemporaire',
            name='session_pec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
