# Generated by Django 3.2.15 on 2023-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0027_sinistretemporaire_session_pec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='veos_code_acte',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='veos_code_affection',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='veos_code_aliment',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='veos_code_cie',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='veos_code_prescripteur',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='veos_code_prestataire',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='veos_id_npol',
        ),
        migrations.RemoveField(
            model_name='sinistretemporaire',
            name='veos_id_sin',
        ),
        migrations.AddField(
            model_name='sinistretemporaire',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
