# Generated by Django 3.2.15 on 2023-09-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0028_auto_20230927_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='taux_tm',
            field=models.FloatField(null=True),
        ),
    ]
