# Generated by Django 3.2.15 on 2023-10-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0030_auto_20231006_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='observation',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
