# Generated by Django 3.2.15 on 2023-10-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0031_sinistre_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiersinistre',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('ANNULE', 'Annule')], default='VALIDE', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('ANNULE', 'Annule')], default='VALIDE', max_length=15, null=True),
        ),
    ]
