# Generated by Django 3.2.15 on 2023-10-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0032_auto_20231011_1052'),
    ]

    operations = [

    ]
