# Generated by Django 3.2.15 on 2023-10-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0033_auto_20231019_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'VALIDE'), ('SUPPRIME', 'ANNULE')], default='VALIDE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'VALIDE'), ('SUPPRIME', 'ANNULE')], default='VALIDE', max_length=15, null=True),
        ),
    ]
