# Generated by Django 3.2.15 on 2023-10-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0034_auto_20231020_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Annule')], default='VALIDE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Annule')], default='VALIDE', max_length=15, null=True),
        ),
    ]
