# Generated by Django 4.1.7 on 2023-10-26 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0068_auto_20231025_1755'),
        ('sinistre', '0035_auto_20231020_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereaudossiersinistre',
            name='periode_comptable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.periodecomptable'),
        ),
        migrations.AddField(
            model_name='bordereausinistre',
            name='periode_comptable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.periodecomptable'),
        ),
    ]
