# Generated by Django 3.2.15 on 2023-10-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0036_bordereaudossiersinistre_periode_comptable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='motif_suppression',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
