# Generated by Django 3.2.15 on 2023-10-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0037_sinistre_motif_suppression'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiersinistre',
            name='of_gestionnaire',
            field=models.BooleanField(default=False),
        ),
    ]
