# Generated by Django 3.2.15 on 2023-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0038_dossiersinistre_of_gestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiersinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('REFUSE', 'Refuse')], default='ATTENTE', max_length=15, null=True),
        ),
    ]
