# Generated by Django 3.2.15 on 2023-10-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0039_dossiersinistre_statut_remboursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='montant_remb_accepte',
            field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='montant_remb_refuse',
            field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='motif_remboursement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('REFUSE', 'Refuse')], default='ATTENTE', max_length=15, null=True),
        ),
    ]
