# Generated by Django 3.2.15 on 2023-10-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0070_modecreation'),
        ('sinistre', '0040_auto_20231027_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiersinistre',
            name='mode_creation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.modecreation'),
        ),
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('REFUSE', 'Refuse')], default='EN ATTENTE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('REFUSE', 'Refuse')], default='EN ATTENTE', max_length=15, null=True),
        ),
    ]
