# Generated by Django 4.1.7 on 2023-10-30 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0069_typeprefinancement_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0040_auto_20231027_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BordereauDossierSinistre',
            new_name='FacturePrestataire',
        ),
        migrations.AlterModelOptions(
            name='factureprestataire',
            options={'verbose_name': 'Facture prestataire', 'verbose_name_plural': 'Factures prestataires'},
        ),
        migrations.AddField(
            model_name='sinistre',
            name='facture_prestataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.factureprestataire'),
        ),
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('REFUSE', 'Refuse')], default='EN ATTENTE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('REFUSE', 'Refuse')], default='EN ATTENTE', max_length=15, null=True),
        ),
        migrations.AlterModelTable(
            name='factureprestataire',
            table='factures_prestataires',
        ),
        migrations.DeleteModel(
            name='BordereauSinistre',
        ),
    ]
