# Generated by Django 3.2.15 on 2023-10-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0041_auto_20231030_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime')], default='VALIDE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime')], default='VALIDE', max_length=15, null=True),
        ),
    ]
