# Generated by Django 4.1.7 on 2023-10-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0041_rename_bordereaudossiersinistre_factureprestataire_and_more'),
        ('sinistre', '0042_auto_20231030_1532'),
    ]

    operations = [
    ]
