# Generated by Django 3.2.15 on 2023-11-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0072_auto_20231030_1532'),
        ('sinistre', '0044_dossiersinistre_bureau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersinistre',
            name='prestataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dossiers_sinistres', to='configurations.prestataire'),
        ),
    ]
