# Generated by Django 4.1.7 on 2023-10-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0044_remboursementsinistre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistre',
            name='montant_remb_accepte',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='montant_remb_refuse',
        ),
        migrations.RemoveField(
            model_name='sinistre',
            name='motif_remboursement',
        ),
    ]
