# Generated by Django 3.2.15 on 2023-11-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0045_alter_dossiersinistre_prestataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiersinistre',
            name='statut_pec',
            field=models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete')], default='EN ATTENTE', max_length=15, null=True),
        ),
    ]
