# Generated by Django 4.1.7 on 2023-11-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0045_remove_sinistre_montant_remb_accepte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursementsinistre',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
