# Generated by Django 4.1.7 on 2023-11-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0044_dossiersinistre_bureau'),
        ('sinistre', '0046_remboursementsinistre_designation'),
    ]

    operations = [
    ]
