# Generated by Django 3.2.15 on 2023-11-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0047_dossiersinistre_statut_prorogation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_pec',
            field=models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_prorogation',
            field=models.CharField(choices=[('ACCORDE', 'Accorde'), ('EN ATTENTE', 'Attente'), ('REJETE', 'Rejete')], default=None, max_length=15, null=True),
        ),
    ]
