# Generated by Django 4.1.7 on 2023-11-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0046_dossiersinistre_statut_pec'),
        ('sinistre', '0048_alter_dossiersinistre_prestataire_and_more'),
    ]

    operations = [
    ]
