# Generated by Django 3.2.15 on 2023-11-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0049_auto_20231103_1737'),
        ('sinistre', '0049_merge_20231103_1224'),
    ]

    operations = [
    ]
