# Generated by Django 3.2.15 on 2023-11-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0050_merge_20231103_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factureprestataire',
            options={'permissions': [], 'verbose_name': 'Facture prestataire', 'verbose_name_plural': 'Factures prestataires'},
        ),
        migrations.AddField(
            model_name='documentdossiersinistre',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=15, null=True),
        ),
    ]
