# Generated by Django 4.0.3 on 2023-11-08 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0073_auto_20231103_1737'),
        ('sinistre', '0051_auto_20231106_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fichier', models.FileField(blank=True, default=None, null=True, upload_to='dossiers_sinistres/bordereaux')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_remb_total', models.FloatField(null=True)),
                ('montant_rejet_total', models.FloatField(null=True)),
                ('montant_accepte_total', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('periode_comptable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.periodecomptable')),
                ('prestataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire')),
            ],
            options={
                'verbose_name': 'Bordereau de validation',
                'verbose_name_plural': 'Bordereaux de validations',
                'db_table': 'bordereau_validation',
                'permissions': [],
            },
        ),
        migrations.AddField(
            model_name='sinistre',
            name='bordereau_validation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.bordereauvalidation'),
        ),
    ]
