# Generated by Django 3.2.15 on 2023-11-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0073_auto_20231103_1737'),
        ('sinistre', '0051_auto_20231106_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiersinistre',
            name='type_remboursement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typeremboursement'),
        ),
    ]
