# Generated by Django 4.0.3 on 2023-11-08 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0073_auto_20231103_1737'),
        ('sinistre', '0052_bordereauvalidation_sinistre_bordereau_validation'),
    ]

    operations = [

    ]
