# Generated by Django 3.2.15 on 2023-11-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0052_dossiersinistre_type_remboursement'),
        ('sinistre', '0053_bordereauoronnancement_and_more'),
    ]

    operations = [
    ]
