# Generated by Django 4.0.3 on 2023-11-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0053_bordereauoronnancement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='is_ges_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='remboursementsinistre',
            name='statut',
            field=models.CharField(choices=[('ACCEPTE', 'Accepte'), ('REFUSE', 'Refuse'), ('NET A PAYER', 'Net A Payer'), ('TAXT', 'Taxt'), ('TAXE FAR', 'Far Taxe')], default='REFUSE', max_length=15, null=True),
        ),
    ]
