# Generated by Django 4.0.3 on 2023-11-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0054_merge_20231114_1136'),
        ('sinistre', '0054_sinistre_is_ges_processed_and_more'),
    ]

    operations = [
    ]
