# Generated by Django 3.2.15 on 2023-11-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0056_bordereauordonnancement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistre',
            name='bordereau_validation',
        ),
    ]
