# Generated by Django 3.2.15 on 2023-11-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0057_auto_20231116_1607'),
    ]

    operations = [
        #ytable innexistant
        #migrations.DeleteModel(
        #    name='BordereauValidation',
        #),
    ]
