# Generated by Django 3.2.15 on 2023-11-22 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0058_bordereauordonnancement_and_more'),
        ('sinistre', '0058_delete_bordereauvalidation'),
    ]

    operations = [
    ]
