# Generated by Django 3.2.15 on 2023-11-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0059_merge_20231122_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiersinistre',
            name='date_survenance',
            field=models.DateTimeField(null=True),
        ),
    ]
