# Generated by Django 3.2.15 on 2023-11-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0061_auto_20231125_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sinistre',
            options={'permissions': [('can_do_ordonnancement', 'Can do ordonnancement')], 'verbose_name': 'Sinistre', 'verbose_name_plural': 'Sinistres'},
        ),
    ]
