# Generated by Django 3.2.15 on 2023-11-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0065_alter_sinistre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('REFUSE', 'Refuse'), ('ANNULE', 'Annule')], default='EN ATTENTE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('REFUSE', 'Refuse'), ('ANNULE', 'Annule')], default='EN ATTENTE', max_length=15, null=True),
        ),
    ]
