# Generated by Django 3.2.15 on 2023-11-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0066_auto_20231129_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureprestataire',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factureprestataire',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime')], default='VALIDE', max_length=15, null=True),
        ),
    ]
