# Generated by Django 3.2.15 on 2023-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0067_auto_20231130_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersinistre',
            name='renseignement_clinique',
            field=models.TextField(null=True),
        ),
    ]
