# Generated by Django 3.2.15 on 2023-12-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0066_auto_20231129_1659'),
        ('sinistre', '0067_auto_20231130_1131'),
    ]

    operations = [
    ]
