# Generated by Django 3.2.15 on 2023-12-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0068_alter_dossiersinistre_renseignement_clinique'),
        ('sinistre', '0068_merge_0066_auto_20231129_1659_0067_auto_20231130_1131'),
    ]

    operations = [
    ]
