# Generated by Django 3.2.15 on 2023-12-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0068_alter_dossiersinistre_renseignement_clinique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon')], default='VALIDE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='factureprestataire',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon')], default='VALIDE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon')], default='VALIDE', max_length=15, null=True),
        ),
    ]
