# Generated by Django 3.2.15 on 2023-12-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0069_auto_20231222_0557'),
        ('sinistre', '0069_merge_20231219_2110'),
    ]

    operations = [
    ]
