# Generated by Django 3.2.15 on 2023-12-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0070_auto_20231227_1610'),
        ('sinistre', '0070_merge_20231227_1029'),
    ]

    operations = [
    ]
