# Generated by Django 3.2.15 on 2024-01-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0059_auto_20240111_1458'),
        ('sinistre', '0071_dossiersinistre_pharmacie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='aliment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ses_sinistres', to='production.aliment'),
        ),
    ]
