# Generated by Django 3.2.15 on 2024-01-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0071_dossiersinistre_pharmacie'),
        ('sinistre', '0071_merge_20231229_1139'),
    ]

    operations = [
    ]
