# Generated by Django 3.2.15 on 2024-01-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0072_alter_sinistre_aliment'),
        ('sinistre', '0072_merge_20240108_1207'),
    ]

    operations = [
    ]
