# Generated by Django 3.2.15 on 2024-01-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0073_dossiersinistre_plafond_accouchement'),
        ('sinistre', '0073_merge_20240116_1015'),
    ]

    operations = [
    ]
