# Generated by Django 3.2.15 on 2024-01-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0073_dossiersinistre_plafond_accouchement'),
        ('sinistre', '0073_factureprestataire_adherent_principal'),
    ]

    operations = [
    ]
