# Generated by Django 3.2.15 on 2024-01-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0074_alter_sinistre_options'),
        ('sinistre', '0074_merge_20240126_1037'),
    ]

    operations = [
    ]
