# Generated by Django 3.2.15 on 2024-01-30 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0137_merge_20240123_0827'),
        ('production', '0068_merge_20240123_0827'),
        ('sinistre', '0076_factureprestataire_bureau'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereauordonnancement',
            name='adherent_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.aliment'),
        ),
        migrations.AddField(
            model_name='bordereauordonnancement',
            name='type_remboursement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typeremboursement'),
        ),
    ]
