# Generated by Django 3.2.15 on 2024-02-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0074_alter_sinistre_options'),
        ('sinistre', '0077_auto_20240130_1730'),
    ]

    operations = [
    ]
