# Generated by Django 3.2.15 on 2024-02-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0078_merge_20240201_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='veos_numero_sin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
