# Generated by Django 3.2.15 on 2024-02-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0075_merge_20240130_1452'),
        ('sinistre', '0079_sinistre_veos_numero_sin'),
    ]

    operations = [
    ]
