# Generated by Django 3.2.15 on 2024-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0080_alter_sinistre_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursementsinistre',
            name='option_refacturation',
            field=models.CharField(choices=[('REFACTURABLE', 'Refacturable'), ('NON REFACTURABLE', 'Non Refacturable')], default='NON REFACTURABLE', max_length=20, null=True),
        ),
    ]
