# Generated by Django 3.2.15 on 2024-02-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0080_alter_sinistre_options'),
        ('sinistre', '0080_merge_20240205_1415'),
    ]

    operations = [
    ]
