# Generated by Django 3.2.15 on 2024-02-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0081_merge_20240214_1637'),
        ('sinistre', '0081_remboursementsinistre_option_refacturation'),
    ]

    operations = [
    ]
