# Generated by Django 3.2.15 on 2024-03-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0081_remboursementsinistre_option_refacturation'),
        ('sinistre', '0082_bordereauordonnancement_statut_paiement'),
    ]

    operations = [
    ]
