# Generated by Django 3.2.15 on 2024-03-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0082_merge_20240222_1041'),
        ('sinistre', '0083_merge_20240308_1635'),
    ]

    operations = [
    ]
