# Generated by Django 3.2.15 on 2024-03-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0158_alter_wsboby_name'),
        ('sinistre', '0084_factureprestataire_fp_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereauordonnancement',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau'),
        ),
    ]
