# Generated by Django 3.2.15 on 2024-03-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0084_factureprestataire_fp_deleted_by'),
        ('sinistre', '0084_merge_20240311_1418'),
    ]

    operations = [
    ]
