# Generated by Django 3.2.15 on 2024-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0085_bordereauordonnancement_bureau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereauordonnancement',
            name='statut_paiement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('ORDONNANCE', 'Ordonnance'), ('PAYE', 'Paye')], default='ORDONNANCE', max_length=15, null=True),
        ),
    ]
