# Generated by Django 3.2.15 on 2024-03-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0086_alter_bordereauordonnancement_statut_paiement'),
        ('sinistre', '0086_merge_20240321_1743'),
    ]

    operations = [
    ]
