# Generated by Django 3.2.15 on 2024-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0087_remboursementsinistre_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='frais_reel',
            field=models.DecimalField(decimal_places=17, max_digits=50, null=True),
        ),
    ]
