# Generated by Django 3.2.15 on 2024-04-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0087_merge_20240329_1051'),
        ('sinistre', '0087_remboursementsinistre_observation'),
    ]

    operations = [
    ]
