# Generated by Django 3.2.15 on 2024-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0088_alter_sinistre_frais_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistretemporaire',
            name='date_reception_facture',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sinistretemporaire',
            name='reference_facture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
