# Generated by Django 3.2.15 on 2024-04-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0088_alter_sinistre_frais_reel'),
        ('sinistre', '0088_merge_20240403_1635'),
    ]

    operations = [
    ]
