# Generated by Django 3.2.15 on 2024-04-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0091_auto_20240409_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='date_reception_facture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sinistretemporaire',
            name='date_reception_facture',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
