# Generated by Django 3.2.15 on 2024-04-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0089_merge_20240408_1359'),
        ('sinistre', '0093_auto_20240411_1154'),
    ]

    operations = [
    ]
