# Generated by Django 3.2.15 on 2024-04-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0094_auto_20240412_1347'),
        ('sinistre', '0094_merge_20240412_0847'),
    ]

    operations = [
    ]
