# Generated by Django 3.2.15 on 2024-04-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0095_auto_20240415_1113'),
        ('sinistre', '0095_merge_20240412_1756'),
    ]

    operations = [
    ]
