# Generated by Django 3.2.15 on 2024-04-15 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0095_auto_20240415_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereauordonnancement',
            name='bo_deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bo_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
