# Generated by Django 3.2.15 on 2024-04-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0098_rename_borderau_ordonnancement_historiqueordonnancementsinistre_bordereau_ordonnancement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiqueordonnancementsinistre',
            old_name='montant',
            new_name='montant_ordonnance',
        ),
    ]
