# Generated by Django 3.2.15 on 2024-04-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0096_merge_20240415_1115'),
        ('sinistre', '0099_rename_montant_historiqueordonnancementsinistre_montant_ordonnance'),
    ]

    operations = [
    ]
