# Generated by Django 3.2.15 on 2024-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0100_dossiersinistre_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereauordonnancement',
            name='montant_total_impaye',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bordereauordonnancement',
            name='montant_total_regle',
            field=models.FloatField(null=True),
        ),
    ]
