# Generated by Django 3.2.15 on 2024-04-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0101_auto_20240425_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bordereauordonnancement',
            old_name='montant_total_regle',
            new_name='montant_total_paye',
        ),
    ]
