# Generated by Django 3.2.15 on 2024-04-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0100_merge_20240417_0836'),
        ('sinistre', '0102_rename_montant_total_regle_bordereauordonnancement_montant_total_paye'),
    ]

    operations = [
    ]
