# Generated by Django 3.2.15 on 2024-05-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0103_merge_20240425_1513'),
        ('sinistre', '0104_alter_sinistre_date_paiement'),
    ]

    operations = [
    ]
