# Generated by Django 3.2.15 on 2024-05-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0105_merge_20240517_1544'),
        ('sinistre', '0106_sinistre_bureau'),
    ]

    operations = [
    ]
