# Generated by Django 3.2.15 on 2024-06-08 12:17

from django.db import migrations, models
import sinistre.models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0106_sinistre_bureau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereauordonnancement',
            name='fichier',
            field=models.FileField(blank=True, default=None, null=True, upload_to=sinistre.models.upload_location_bordereauordonnancement),
        ),
        migrations.AlterField(
            model_name='documentdossiersinistre',
            name='fichier',
            field=models.FileField(blank=True, default=None, null=True, upload_to=sinistre.models.upload_location_documentdossiersinistre),
        ),
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('ACCEPTE PARTIELLEMENT', 'Accepte Partiellement'), ('REFUSE', 'Refuse'), ('ANNULE', 'Annule')], default='EN ATTENTE', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='factureprestataire',
            name='fichier',
            field=models.FileField(blank=True, default=None, null=True, upload_to=sinistre.models.upload_location_factureprestataire),
        ),
        migrations.AlterField(
            model_name='paiementcomptable',
            name='fichier',
            field=models.FileField(blank=True, default=None, null=True, upload_to=sinistre.models.upload_location_paiementcomptable),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('ACCEPTE PARTIELLEMENT', 'Accepte Partiellement'), ('REFUSE', 'Refuse'), ('ANNULE', 'Annule')], default='EN ATTENTE', max_length=25, null=True),
        ),
    ]
