# Generated by Django 3.2.15 on 2024-06-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0107_auto_20240608_1217'),
        ('sinistre', '0107_merge_0105_merge_20240517_1544_0106_sinistre_bureau'),
    ]

    operations = [
    ]
