# Generated by Django 3.2.15 on 2024-06-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0107_auto_20240607_1455'),
        ('sinistre', '0107_auto_20240608_1217'),
    ]

    operations = [
    ]
