# Generated by Django 3.2.15 on 2024-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0108_merge_0107_auto_20240607_1455_0107_auto_20240608_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementcomptable',
            name='uuid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
