# Generated by Django 3.2.15 on 2024-06-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0108_merge_0107_auto_20240607_1455_0107_auto_20240608_1217'),
        ('sinistre', '0109_merge_20240614_1309'),
    ]

    operations = [
    ]
