# Generated by Django 3.2.15 on 2024-07-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0200_bordereaulettrecheque'),
        ('sinistre', '0109_paiementcomptable_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementcomptable',
            name='bordereau_lettre_cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bordereaulettrecheque'),
        ),
    ]
