# Generated by Django 3.2.15 on 2024-07-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0109_paiementcomptable_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='taux_retenue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
