# Generated by Django 3.2.15 on 2024-07-26 16:04

from django.db import migrations, models
import sinistre.models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0110_demanderemboursementmobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='acquittee_laboratoire',
            field=models.FileField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='facture_normalisee',
            field=models.FileField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='prescription_medical',
            field=models.FileField(blank=True, default=None, null=True),
        ),
    ]
