# Generated by Django 3.2.15 on 2024-08-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0114_merge_20240806_1656'),
        ('configurations', '0203_auto_20240726_1108'),
        ('sinistre', '0110_paiementcomptable_bordereau_lettre_cheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRemboursementMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sinistre', models.DateField(blank=True)),
                ('montant_a_rembourser', models.DecimalField(decimal_places=2, max_digits=20)),
                ('numero_remboursement', models.CharField(blank=True, max_length=100, null=True)),
                ('prescription_medical', models.FileField(blank=True, default=None, upload_to='sinistre/documents/prescription_medical/')),
                ('facture_normalisee', models.FileField(blank=True, default=None, upload_to='sinistre/documents/facture_normalisee/')),
                ('acquittee_laboratoire', models.FileField(blank=True, default=None, null=True, upload_to='sinistre/documents/acquittee_laboratoire/')),
                ('autre_document', models.FileField(blank=True, null=True, upload_to='sinistre/documents/autres/')),
                ('statut', models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('ACCEPTE PARTIELLEMENT', 'Accepte Partiellement'), ('REFUSE', 'Refuse'), ('ANNULE', 'Annule')], default='EN ATTENTE', max_length=25)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.acte')),
                ('adherent_principal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.aliment')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='beneficiaire_remboursements', to='production.aliment')),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('mode_remboursement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.modereglement')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire')),
            ],
            options={
                'verbose_name': 'Demande de remboursement mobile',
                'verbose_name_plural': 'Demandes de remboursement mobiles',
                'db_table': 'demande_remboursement_mobile',
            },
        ),
    ]
