# Generated by Django 3.2.15 on 2024-06-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0109_paiementcomptable_uuid'),
        ('sinistre', '0110_merge_20240614_1858'),
    ]

    operations = [
    ]
