# Generated by Django 3.2.15 on 2024-07-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0110_paiementcomptable_bordereau_lettre_cheque'),
        ('sinistre', '0111_merge_20240620_1214'),
    ]

    operations = [
    ]
