# Generated by Django 3.2.15 on 2024-07-29 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0198_auto_20240703_1638'),
        ('production', '0110_merge_20240726_1026'),
        ('sinistre', '0111_auto_20240726_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='acte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.acte'),
        ),
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='adherent_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.aliment'),
        ),
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='beneficiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='beneficiaire_remboursements', to='production.aliment'),
        ),
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau'),
        ),
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='date_sinistre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='mode_remboursement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.modereglement'),
        ),
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='prestataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire'),
        ),
    ]
