# Generated by Django 3.2.15 on 2024-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0112_auto_20240729_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='acquittee_laboratoire',
            field=models.FileField(blank=True, default=None, null=True, upload_to='sinistre/documents/acquittee_laboratoire/'),
        ),
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='autre_document',
            field=models.FileField(blank=True, null=True, upload_to='sinistre/documents/autres/'),
        ),
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='facture_normalisee',
            field=models.FileField(blank=True, default=None, null=True, upload_to='sinistre/documents/facture_normalisee/'),
        ),
        migrations.AlterField(
            model_name='demanderemboursementmobile',
            name='prescription_medical',
            field=models.FileField(blank=True, default=None, null=True, upload_to='sinistre/documents/prescription_medical/'),
        ),
    ]
