# Generated by Django 3.2.15 on 2024-07-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0113_auto_20240730_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemandeRemboursementMobile',
        ),
    ]
