# Generated by Django 3.2.15 on 2024-08-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0110_sinistre_taux_retenue'),
        ('sinistre', '0111_demanderemboursementmobile'),
        ('sinistre', '0114_delete_demanderemboursementmobile'),
    ]

    operations = [
    ]
