# Generated by Django 3.2.15 on 2024-08-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0115_merge_20240821_1732'),
        ('sinistre', '0115_merge_20240822_0931'),
    ]

    operations = [
    ]
