# Generated by Django 3.2.15 on 2024-08-22 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sinistre.models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0116_auto_20240822_0955'),
    ]

    operations = [
    ]
