# Generated by Django 3.2.15 on 2024-08-22 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sinistre.models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0206_auto_20240822_1720'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0116_auto_20240822_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureCompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default=sinistre.models.generate_random_invoice_number, max_length=20, unique=True)),
                ('montant_total', models.BigIntegerField()),
                ('montant_regle', models.BigIntegerField(default=0, null=True)),
                ('montant_restant', models.BigIntegerField(null=True)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, default=None, null=True, upload_to='factures/fact_compagnies')),
                ('statut', models.CharField(choices=[('SOLDE', 'Solde'), ('NON SOLDE', 'Non Solde')], default='NON SOLDE', max_length=15, null=True)),
                ('statut_validite', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('compagnie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('devise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.devise')),
            ],
            options={
                'verbose_name': "Facture d'une compagnie",
                'verbose_name_plural': 'Factures des compagnies',
                'db_table': 'facture_compagnie',
            },
        ),
        migrations.CreateModel(
            name='ReglementCompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_piece', models.CharField(blank=True, max_length=50, null=True)),
                ('banque_emettrice', models.CharField(blank=True, max_length=255, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('date_reglement', models.DateField(blank=True, null=True)),
                ('observation', models.CharField(max_length=255, null=True)),
                ('motif_annulation', models.CharField(max_length=255, null=True)),
                ('statut_validite', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.banque')),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('compagnie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('compte_tresorerie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.comptetresorerie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('devise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.devise')),
                ('mode_reglement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.modereglement')),
            ],
            options={
                'verbose_name': 'Reglement compagnie',
                'verbose_name_plural': 'Reglements faits par les compagnies',
                'db_table': 'reglement_compagnie',
            },
        ),
        migrations.CreateModel(
            name='ReglementFactureCompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_regle', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('observation', models.CharField(max_length=255, null=True)),
                ('statut_validite', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('facture_compagnie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.facturecompagnie')),
                ('reglement_compagnie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.reglementcompagnie')),
            ],
            options={
                'verbose_name': 'Reglement facture',
                'verbose_name_plural': 'Reglement facture',
                'db_table': 'reglement_facture_compagnie',
            },
        ),
        migrations.AddField(
            model_name='sinistre',
            name='facture_compagnie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.facturecompagnie'),
        ),
    ]
