# Generated by Django 3.2.15 on 2024-08-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0116_auto_20240822_0955'),
        ('sinistre', '0116_merge_20240822_0935'),
    ]

    operations = [
    ]
