# Generated by Django 3.2.15 on 2024-08-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('sinistre', '0117_auto_20240822_1720'),
        ('sinistre', '0117_merge_20240822_1001'),
    ]

    operations = [
    ]
