# Generated by Django 3.2.15 on 2024-08-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('sinistre', '0116_auto_20240821_1830'),
        ('sinistre', '0112_auto_20240729_1546'),
    ]

    operations = [
    ]
