# Generated by Django 3.2.15 on 2024-09-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0117_auto_20240822_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementcomptable',
            name='observation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paiementcomptable',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True),
        ),
    ]
