# Generated by Django 3.2.15 on 2024-09-03 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0116_auto_20240822_1830'),
        # ('sinistre', '0118_auto_20240903_1700'),
        ('sinistre', '0118_merge_0116_auto_20240821_1830_0117_auto_20240822_1720'),
    ]

    operations = [
    ]
