# Generated by Django 3.2.15 on 2024-09-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0119_merge_20240903_2223'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='sinistre',
        #    name='date_ordonnancement',
        #    field=models.DateTimeField(null=True),
        #),
        #migrations.AddField(
        #    model_name='sinistre',
        #    name='date_reglement',
        #    field=models.DateTimeField(null=True),
        #),
        #migrations.AddField(
        #    model_name='sinistre',
        #    name='far',
        #    field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        #),
        #migrations.AddField(
        #    model_name='sinistre',
        #    name='import_stats',
        #    field=models.CharField(blank=True, max_length=255, null=True),
        #),
        #migrations.AddField(
        #    model_name='sinistre',
        #    name='net_regle',
        #    field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        #),
        #migrations.AddField(
        #    model_name='sinistre',
        #    name='numero_bordereau',
        #    field=models.CharField(blank=True, max_length=255, null=True),
        #),
        #migrations.AddField(
        #    model_name='sinistre',
        #    name='numero_lettre_cheque',
        #    field=models.CharField(blank=True, max_length=255, null=True),
        #),
        #migrations.AddField(
        #    model_name='sinistre',
        #    name='ticket_prefinance',
        #    field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        #),
        #migrations.AddField(
        #    model_name='sinistre',
        #    name='tps',
        #    field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        #),
    ]
