# Generated by Django 3.2.15 on 2024-09-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0119_merge_20240903_2157'),
        ('sinistre', '0119_merge_20240903_2223'),
    ]

    operations = [
    ]
