# Generated by Django 3.2.15 on 2024-09-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0120_auto_20240904_1544'),
    ]

    operations = [
        
    ]
