# Generated by Django 3.2.15 on 2024-09-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0120_merge_20240903_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='date_ordonnancement',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='date_reglement',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='far',
            field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='import_stats',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='net_regle',
            field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='numero_bordereau',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='numero_lettre_cheque',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='ticket_prefinance',
            field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='tps',
            field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='dossiersinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('ACCEPTE PARTIELLEMENT', 'Accepte Partiellement'), ('REFUSE', 'Refuse'), ('ANNULE', 'Annule')], default='EN ATTENTE', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut_remboursement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('DEMANDE', 'Demande'), ('ACCEPTE', 'Accepte'), ('ACCEPTE PARTIELLEMENT', 'Accepte Partiellement'), ('REFUSE', 'Refuse'), ('ANNULE', 'Annule')], default='EN ATTENTE', max_length=25, null=True),
        ),
    ]
