# Generated by Django 3.2.15 on 2024-09-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0120_auto_20240904_1544'),
        ('sinistre', '0121_auto_20240903_2237'),
    ]

    operations = [
    ]
