# Generated by Django 3.2.15 on 2024-09-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0121_auto_20240904_1708'),
        ('sinistre', '0122_merge_0120_auto_20240904_1544_0121_auto_20240903_2237'),
    ]

    operations = [
    ]
