# Generated by Django 3.2.15 on 2024-09-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0123_merge_20240904_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='montant_refacture_client',
            field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='montant_refacture_compagnie',
            field=models.DecimalField(decimal_places=16, max_digits=50, null=True),
        ),
    ]
