# Generated by Django 3.2.15 on 2024-09-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0117_paiementcomptable_observation_and_more'),
        ('sinistre', '0123_bordereauordonnancement_assure'),
    ]

    operations = [
    ]
