# Generated by Django 5.1.1 on 2024-09-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sinistre", "0117_paiementcomptable_observation_and_more"),
        ("sinistre", "0123_bordereauordonnancement_assure"),
    ]

    operations = []
