# Generated by Django 3.2.15 on 2024-09-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0117_paiementcomptable_observation_and_more'),
        ('sinistre', '0122_auto_20240909_1218'),
        ('sinistre', '0123_bordereauordonnancement_assure'),
        ('sinistre', '0124_auto_20240904_1813'),
    ]

    operations = [
    ]
