# Generated by Django 3.2.15 on 2024-09-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0118_auto_20240903_1700'),
        ('sinistre', '0125_merge_20240912_1000'),
    ]

    operations = [
    ]
