# Generated by Django 3.2.15 on 2024-09-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0124_merge_20240911_1536'),
        ('sinistre', '0128_tracketat_tracketatfacture_trackfacture'),
    ]

    operations = [
    ]
