# Generated by Django 3.2.15 on 2024-09-18 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0218_periodeveos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0129_merge_20240914_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackEtapeFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
            ],
            options={
                'verbose_name': 'Etat Facture',
                'verbose_name_plural': 'Etat Facture',
                'db_table': 'track_etape_facture',
            },
        ),
        migrations.AlterModelOptions(
            name='tracketat',
            options={'verbose_name': 'Etape', 'verbose_name_plural': 'Etape'},
        ),
        migrations.AddField(
            model_name='trackfacture',
            name='prestataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire'),
        ),
        migrations.AlterModelTable(
            name='tracketat',
            table='track_etape',
        ),
        migrations.DeleteModel(
            name='TrackEtatFacture',
        ),
        migrations.AddField(
            model_name='tracketapefacture',
            name='track_facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.trackfacture'),
        ),
    ]
