# Generated by Django 3.2.15 on 2024-09-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0124_merge_20240913_0856'),
        ('sinistre', '0130_auto_20240918_1800'),
    ]

    operations = [
    ]
