# Generated by Django 3.2.15 on 2024-09-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0131_merge_20240919_1257'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='sinistre',
        #    name='recalcule_refact_garant_client',
        #    field=models.BooleanField(default=False),
        #),
    ]
