# Generated by Django 3.2.15 on 2024-09-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0131_merge_20240919_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackEtat',
            new_name='TrackEtape',
        ),
        migrations.AlterModelOptions(
            name='tracketapefacture',
            options={'verbose_name': 'Etape Facture', 'verbose_name_plural': 'Etapes Factures'},
        ),
        migrations.RemoveField(
            model_name='tracketapefacture',
            name='etat',
        ),
        migrations.AddField(
            model_name='sinistre',
            name='recalcule_refact_garant_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracketapefacture',
            name='etape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.tracketape'),
        ),
    ]
