# Generated by Django 3.2.15 on 2024-09-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0132_sinistre_recalcule_refact_garant_client'),
        ('sinistre', '0133_rename_recalcule_refact_garant_client_sinistre_recalcule_mt_refact_garant_client'),
    ]

    operations = [
    ]
