# Generated by Django 3.2.15 on 2024-10-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0134_merge_20240924_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiersinistre',
            name='date_traitement_sinistre_bymedecin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiersinistre',
            name='has_sinistre_traite_bymedecin',
            field=models.BooleanField(default=False),
        ),
    ]
