# Generated by Django 3.2.15 on 2024-10-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0136_paiementcomptable_banque_emettrice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='nombre_demande_initial',
            field=models.IntegerField(null=True),
        ),
    ]
