# Generated by Django 3.2.15 on 2024-10-21 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0137_sinistre_nombre_demande_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementcomptable',
            name='pc_deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pc_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
