# Generated by Django 3.2.15 on 2024-10-21 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0138_paiementcomptable_pc_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePaiementComptableSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=16, max_digits=50, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('paiement_comptable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.paiementcomptable')),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.sinistre')),
            ],
            options={
                'verbose_name': 'Historique paiement comptable sinistre',
                'verbose_name_plural': 'Historique paiement comptable sinistre',
                'db_table': 'historique_paiement_comptable_sinistre',
            },
        ),
    ]
