# Generated by Django 3.2.15 on 2024-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0140_dossiersinistre_soins_a_l_entrange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersinistre',
            name='soins_a_l_entrange',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='soins_a_l_entrange',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
