# Generated by Django 3.2.15 on 2024-11-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0141_auto_20241105_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossiersinistre',
            options={'verbose_name': 'Sinistre', 'verbose_name_plural': 'Liste des sinistres'},
        ),
    ]
