# Generated by Django 3.2.15 on 2024-11-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0229_auto_20241125_1633'),
        ('sinistre', '0141_auto_20241105_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossiersinistre',
            options={'verbose_name': 'Sinistre', 'verbose_name_plural': 'Liste des sinistres'},
        ),
        migrations.AlterField(
            model_name='reglementcompagnie',
            name='devise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.devise'),
        ),
    ]
