# Generated by Django 3.2.15 on 2025-01-09 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0002_initial'),
        ('sinistre', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Comptes comptables',
                'db_table': 'compte_comptable',
            },
        ),
        migrations.CreateModel(
            name='EncaissementCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_com_courtage', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('montant_com_gestion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('type_commission', models.CharField(choices=[('COURTAGE', 'Courtage'), ('GESTION', 'Gestion')], default=None, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.operation')),
                ('reglement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='encaissement_commissions', related_query_name='encaissement_commission', to='production.reglement')),
            ],
            options={
                'verbose_name': 'Encaissement de commission',
                'verbose_name_plural': 'Encaissements de commissions',
                'db_table': 'encaissement_commission',
            },
        ),
        migrations.CreateModel(
            name='BordereauOrdonnance',
            fields=[
            ],
            options={
                'verbose_name': 'Bord. ordonnancé',
                'verbose_name_plural': 'Bordx ordonnancés',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sinistre.bordereauordonnancement',),
        ),
        migrations.CreateModel(
            name='ReglementApporteurs',
            fields=[
            ],
            options={
                'verbose_name': 'Reglement apporteurs',
                'verbose_name_plural': 'Reglements apporteurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.reglement',),
        ),
        migrations.CreateModel(
            name='ReglementReverseCompagnie',
            fields=[
            ],
            options={
                'verbose_name': 'Reglement compagnie',
                'verbose_name_plural': 'Reglements compagnie',
                'permissions': [('can_do_reglement_compagnie', 'Peut faire des règlements compagnies')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.reglement',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(blank=True, max_length=1, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('compte_comptable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comptabilite.comptecomptable')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('encaissement_commission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journals', related_query_name='journal', to='comptabilite.encaissementcommission')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'db_table': 'journal',
            },
        ),
    ]
