# Generated by Django 3.2.15 on 2024-01-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0071_dossiersinistre_pharmacie'),
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauOrdonnance',
            fields=[
            ],
            options={
                'verbose_name': 'Bord. ordonnancé',
                'verbose_name_plural': 'Bordx ordonnancés',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sinistre.bordereauordonnancement',),
        ),
    ]
