# Generated by Django 3.2.15 on 2024-01-31 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_bordereauordonnance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reglementcompagnie',
            options={'permissions': [('can_do_reglement_compagnie', 'Peut faire des règlements compagnies')], 'verbose_name': 'Reglement compagnie', 'verbose_name_plural': 'Reglements compagnie'},
        ),
    ]
