# Generated by Django 3.2.15 on 2024-03-11 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0153_natureoperation_code'),
        ('sinistre', '0082_bordereauordonnancement_statut_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0079_operationreglement'),
        ('comptabilite', '0003_alter_reglementcompagnie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_beneficiaire', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_iban', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_piece', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('nombre_quittances', models.IntegerField(blank=True, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, default=None, null=True, upload_to='dossiers_sinistres/bordereaux_paiements_comptables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aliment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.aliment')),
                ('banque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.banque')),
                ('bordereau_ordonnancement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sinistre.bordereauordonnancement')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('mode_reglement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.modereglement')),
                ('prestataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.prestataire')),
            ],
            options={
                'verbose_name': 'Paiement comptable',
                'verbose_name_plural': 'Paiements comptable',
                'db_table': 'paiement_comptable',
            },
        ),
    ]
