# Generated by Django 3.2.15 on 2024-03-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0158_alter_wsboby_name'),
        ('comptabilite', '0005_auto_20240326_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiementcomptable',
            old_name='aliment',
            new_name='adherent_principal',
        ),
        migrations.AddField(
            model_name='paiementcomptable',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau'),
        ),
    ]
