# Generated by Django 3.2.15 on 2024-03-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0006_auto_20240326_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiementcomptable',
            old_name='nombre_quittances',
            new_name='nombre_sinistres',
        ),
    ]
