# Generated by Django 3.2.15 on 2024-04-09 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0086_reglement_date_encaissement_commission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptabilite', '0007_rename_nombre_quittances_paiementcomptable_nombre_sinistres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncaissementCommission',
        ),
        migrations.CreateModel(
            name='EncaissementCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_com_courtage', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('montant_com_gestion', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('reglement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.reglement')),
            ],
            options={
                'verbose_name': 'Encaissement de commission',
                'verbose_name_plural': 'Encaissements de commissions',
                'db_table': 'encaissement_commission',
            },
        ),
    ]
