# Generated by Django 3.2.15 on 2024-04-15 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0086_reglement_date_encaissement_commission'),
        ('comptabilite', '0010_comptecomptable_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaissementcommission',
            name='reglement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='encaissement_commissions', related_query_name='encaissement_commission', to='production.reglement'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='encaissement_commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journals', related_query_name='journal', to='comptabilite.encaissementcommission'),
        ),
    ]
