# Generated by Django 3.2.15 on 2024-04-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0011_auto_20240415_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
