# Generated by Django 3.2.15 on 2024-04-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0012_alter_journal_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
