# Generated by Django 3.2.15 on 2024-05-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0013_alter_journal_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaiementComptable',
        ),
    ]
