# Generated by Django 3.2.15 on 2024-05-29 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0175_remove_compagnie_has_taux_multiple'),
        ('production', '0095_auto_20240528_1133'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptabilite', '0014_delete_paiementcomptable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureCompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('montant_total', models.BigIntegerField()),
                ('montant_regle', models.BigIntegerField(null=True)),
                ('montant_restant', models.BigIntegerField(null=True)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('IMPAYE', 'Impaye'), ('PAYE', 'Paye')], default='IMPAYE', max_length=15, null=True)),
                ('statut_validite', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('compagnie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('devise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.devise')),
            ],
            options={
                'verbose_name': "Facture d'une compagnie",
                'verbose_name_plural': 'Factures des compagnies',
                'db_table': 'facture_compagnie',
            },
        ),
        migrations.CreateModel(
            name='ReglementFactureCompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_regle', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('observation', models.CharField(max_length=255, null=True)),
                ('statut_validite', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('facture_compagnie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comptabilite.facturecompagnie')),
            ],
            options={
                'verbose_name': 'Reglement facture',
                'verbose_name_plural': 'Reglement facture',
                'db_table': 'reglement_facture_compagnie',
            },
        ),
        migrations.DeleteModel(
            name='ReglementCompagnie',
        ),
        migrations.CreateModel(
            name='ReglementReverseCompagnie',
            fields=[
            ],
            options={
                'verbose_name': 'Reglement compagnie',
                'verbose_name_plural': 'Reglements compagnie',
                'permissions': [('can_do_reglement_compagnie', 'Peut faire des règlements compagnies')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.reglement',),
        ),
        migrations.CreateModel(
            name='ReglementCompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_piece', models.CharField(blank=True, max_length=50, null=True)),
                ('banque_emettrice', models.CharField(blank=True, max_length=255, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('date_reglement', models.DateField(blank=True, null=True)),
                ('observation', models.CharField(max_length=255, null=True)),
                ('motif_annulation', models.CharField(max_length=255, null=True)),
                ('statut_validite', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.banque')),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('compagnie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('compte_tresorerie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.comptetresorerie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('devise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.devise')),
                ('mode_reglement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.modereglement')),
            ],
            options={
                'verbose_name': 'Reglement compagnie',
                'verbose_name_plural': 'Reglements faits par les compagnies',
                'db_table': 'reglement_compagnie',
            },
        ),
        migrations.AddField(
            model_name='reglementfacturecompagnie',
            name='reglement_compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comptabilite.reglementcompagnie'),
        ),
    ]
