# Generated by Django 3.2.15 on 2024-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0015_auto_20240529_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaissementcommission',
            name='type_commission',
            field=models.CharField(choices=[('COURTAGE', 'Courtage'), ('GESTION', 'Gestion')], default=None, max_length=15, null=True),
        ),
    ]
