# Generated by Django 3.2.15 on 2024-08-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0017_auto_20240822_1720'),
        #('comptabilite', '0017_merge_20240722_0948'),
    ]

    operations = [
    ]
