# Generated by Django 3.2.15 on 2024-11-28 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secteuractivite',
            options={'verbose_name': "Secteurs d'activité", 'verbose_name_plural': "Secteurs d'activité"},
        ),
        migrations.AlterModelTable(
            name='secteuractivite',
            table='secteur_activite',
        ),
    ]
