# Generated by Django 3.2.19 on 2023-06-25 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_bareme_periodicite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bareme',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bareme',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deleted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
