# Generated by Django 3.2.15 on 2024-11-28 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_remove_apporteur_apporteur_international'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0003_auto_20241128_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquepolice',
            name='placement_gestion',
        ),
        migrations.RemoveField(
            model_name='historiquepolice',
            name='programme_international',
        ),
        migrations.RemoveField(
            model_name='historiquepolice',
            name='taux_com_gestion',
        ),
        migrations.RemoveField(
            model_name='historiquepolice',
            name='veos_code_cie',
        ),
        migrations.RemoveField(
            model_name='historiquepolice',
            name='veos_code_client',
        ),
        migrations.RemoveField(
            model_name='historiquepolice',
            name='veos_id_npol',
        ),
        migrations.RemoveField(
            model_name='historiquepolice',
            name='veos_id_pol',
        ),
        migrations.CreateModel(
            name='PoliceGarantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.FloatField(blank=True, null=True)),
                ('capital', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pg_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('garantie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.garantie')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pg_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Police Garanties',
                'verbose_name_plural': 'Police Garanties',
                'db_table': 'police_garantie',
            },
        ),
    ]
