# Generated by Django 3.2.19 on 2023-07-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_client_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adresse_2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='adresse_3',
        ),
    ]
