# Generated by Django 3.2.19 on 2023-07-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20230712_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='numero_provisoire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
