# Generated by Django 3.2.15 on 2024-11-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_remove_apporteur_apporteur_international'),
        ('production', '0005_autrerisque'),
    ]

    operations = [
        migrations.AddField(
            model_name='policegarantie',
            name='formule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.formule'),
        ),
    ]
