# Generated by Django 3.2.19 on 2023-07-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20230712_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='code_client_veos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
