# Generated by Django 3.2.15 on 2024-11-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_policegarantie_formule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='placement_gestion',
        ),
        migrations.RemoveField(
            model_name='police',
            name='programme_international',
        ),
    ]
