# Generated by Django 3.2.19 on 2023-07-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_police_code_client_veos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='police',
            old_name='code_client_veos',
            new_name='veos_code_cie',
        ),
        migrations.AddField(
            model_name='police',
            name='veos_code_client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
