# Generated by Django 3.2.15 on 2024-11-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20241128_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policegarantie',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='policegarantie',
            name='formule',
        ),
    ]
