# Generated by Django 3.2.15 on 2024-12-05 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_remove_paramproduitcompagnie_taux_com_gestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0008_auto_20241128_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police'),
        ),
        migrations.CreateModel(
            name='HistoriqueVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_immatriculation', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_immat_provisoire', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=25, null=True)),
                ('numero_parc', models.CharField(blank=True, max_length=25, null=True)),
                ('marque', models.CharField(blank=True, max_length=50, null=True)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('proprietaire', models.CharField(blank=True, max_length=50, null=True)),
                ('conducteur', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('valeur_neuve', models.CharField(blank=True, max_length=50, null=True)),
                ('valeur_actuelle', models.CharField(blank=True, max_length=50, null=True)),
                ('puissance', models.CharField(blank=True, max_length=50, null=True)),
                ('poids_a_vide', models.CharField(blank=True, max_length=50, null=True)),
                ('poids_a_charge', models.CharField(blank=True, max_length=50, null=True)),
                ('date_mis_en_circulation', models.DateField(blank=True, null=True)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carburant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.carburant')),
                ('carosserie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.carosserie')),
                ('categorie_vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.categorievehicule')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('formule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.formule')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='hvh_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.usage')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.vehicule')),
            ],
            options={
                'verbose_name': 'Historique Véhicules',
                'verbose_name_plural': 'Historique Véhicules',
                'db_table': 'historique_vehicules',
            },
        ),
    ]
