# Generated by Django 3.2.19 on 2023-07-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_formulegarantie_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulegarantie',
            name='libelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
