# Generated by Django 3.2.15 on 2024-12-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20241205_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiquevehicule',
            old_name='place',
            new_name='places_assises',
        ),
    ]
