# Generated by Django 3.2.19 on 2023-07-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_alter_formulegarantie_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='veos_id_npol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='police',
            name='veos_id_npol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
