# Generated by Django 3.2.15 on 2024-12-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_rename_place_historiquevehicule_places_assises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='place',
            new_name='places_assises',
        ),
    ]
