# Generated by Django 3.2.19 on 2023-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_auto_20230714_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
    ]
