# Generated by Django 3.2.15 on 2024-12-09 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_remove_paramproduitcompagnie_taux_com_gestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0012_rename_place_vehicule_places_assises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquepolice',
            name='compagnie',
        ),
        migrations.RemoveField(
            model_name='historiquevehicule',
            name='police',
        ),
        migrations.RemoveField(
            model_name='police',
            name='apporteur',
        ),
        migrations.RemoveField(
            model_name='police',
            name='autres_taxes',
        ),
        migrations.RemoveField(
            model_name='police',
            name='calcul_tm',
        ),
        migrations.RemoveField(
            model_name='police',
            name='commission_annuelle',
        ),
        migrations.RemoveField(
            model_name='police',
            name='commission_courtage',
        ),
        migrations.RemoveField(
            model_name='police',
            name='commission_gestion',
        ),
        migrations.RemoveField(
            model_name='police',
            name='commission_intermediaires',
        ),
        migrations.RemoveField(
            model_name='police',
            name='compagnie',
        ),
        migrations.RemoveField(
            model_name='police',
            name='cout_police_compagnie',
        ),
        migrations.RemoveField(
            model_name='police',
            name='cout_police_courtier',
        ),
        migrations.RemoveField(
            model_name='police',
            name='date_debut_effet',
        ),
        migrations.RemoveField(
            model_name='police',
            name='date_fin_effet',
        ),
        migrations.RemoveField(
            model_name='police',
            name='fractionnement',
        ),
        migrations.RemoveField(
            model_name='police',
            name='mode_reglement',
        ),
        migrations.RemoveField(
            model_name='police',
            name='mode_renouvellement',
        ),
        migrations.RemoveField(
            model_name='police',
            name='prime_ht',
        ),
        migrations.RemoveField(
            model_name='police',
            name='prime_net',
        ),
        migrations.RemoveField(
            model_name='police',
            name='prime_ttc',
        ),
        migrations.RemoveField(
            model_name='police',
            name='regularisation',
        ),
        migrations.RemoveField(
            model_name='police',
            name='taux_com_courtage',
        ),
        migrations.RemoveField(
            model_name='police',
            name='taux_com_courtage_terme',
        ),
        migrations.RemoveField(
            model_name='police',
            name='taux_com_gestion',
        ),
        migrations.RemoveField(
            model_name='police',
            name='taxe',
        ),
        migrations.CreateModel(
            name='PoliceAssureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.client')),
                ('compagnie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('historique_police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.historiquepolice')),
            ],
            options={
                'verbose_name': 'Police Assureurs',
                'verbose_name_plural': 'Police Assureurs',
                'db_table': 'police_assureurs',
            },
        ),
    ]
