# Generated by Django 3.2.15 on 2024-12-09 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_remove_paramproduitcompagnie_taux_com_gestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0013_auto_20241209_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimentpolice',
            old_name='date_debut',
            new_name='date_entree',
        ),
        migrations.RenameField(
            model_name='alimentpolice',
            old_name='date_fin',
            new_name='date_mis_en_circulation',
        ),
        migrations.RemoveField(
            model_name='alimentpolice',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='autrerisque',
            name='client',
        ),
        migrations.RemoveField(
            model_name='autrerisque',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='autrerisque',
            name='police',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='conducteur',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='date_entree',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='date_mis_en_circulation',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='date_sortie',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='numero_parc',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='police',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='valeur_actuelle',
        ),
        migrations.AddField(
            model_name='alimentpolice',
            name='commentaire',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='alimentpolice',
            name='conducteur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alimentpolice',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimentpolice',
            name='existed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alimpo_existed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alimentpolice',
            name='historique_police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.historiquepolice'),
        ),
        migrations.AddField(
            model_name='alimentpolice',
            name='numero_parc',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='alimentpolice',
            name='proprietaire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alimentpolice',
            name='usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.usage'),
        ),
        migrations.AddField(
            model_name='alimentpolice',
            name='valeur_actuelle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alimentpolice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alimpo_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alimentpolice',
            name='statut',
            field=models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='alimentpolice',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alimpo_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autrerisque',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='autr_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autrerisque',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='autr_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
