# Generated by Django 3.2.19 on 2023-07-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_auto_20230714_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='telephone_fixe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='telephone_mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
