# Generated by Django 3.2.15 on 2024-12-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_auto_20241209_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquepolice',
            name='date_du_jour',
            field=models.DateTimeField(null=True),
        ),
    ]
