# Generated by Django 3.2.15 on 2024-12-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_remove_paramproduitcompagnie_taux_com_gestion'),
        ('production', '0015_historiquepolice_date_du_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='autrerisque',
            name='historique_police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.historiquepolice'),
        ),
        migrations.AlterField(
            model_name='police',
            name='type_assurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typeassurance'),
        ),
    ]
