# Generated by Django 3.2.19 on 2023-07-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_auto_20230714_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=10),
        ),
    ]
