# Generated by Django 3.2.19 on 2023-07-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_alter_aliment_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulegarantie',
            name='plafond_conso_famille',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='formulegarantie',
            name='plafond_conso_individuelle',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
    ]
