# Generated by Django 3.2.15 on 2024-12-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_auto_20241210_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police',
            name='type_assurance',
        ),
    ]
