# Generated by Django 3.2.19 on 2023-07-26 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0017_auto_20230722_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulegarantie',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fg_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulegarantie',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fg_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
