# Generated by Django 3.2.15 on 2023-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_auto_20230726_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulegarantie',
            name='garantis_pharmacie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
