# Generated by Django 3.2.15 on 2024-12-11 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_police_type_assurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquepolice',
            name='date_du_jour',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historiques', to='production.police'),
        ),
    ]
