# Generated by Django 3.2.15 on 2023-08-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0033_sinistreveos_num_compagnie'),
        ('production', '0019_alter_aliment_qualite_beneficiaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='civilite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.civilite'),
        ),
    ]
