# Generated by Django 3.2.15 on 2024-12-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_auto_20241211_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquepolice',
            name='date_du_jour',
            field=models.DateTimeField(null=True),
        ),
    ]
