# Generated by Django 3.2.15 on 2023-08-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_formulegarantie_garantis_pharmacie'),
        ('production', '0020_alter_aliment_civilite'),
    ]

    operations = [
    ]
