# Generated by Django 3.2.15 on 2024-12-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_typecompagnie'),
        ('production', '0020_alter_historiquepolice_date_du_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeassureur',
            name='type_compagnie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typecompagnie'),
        ),
    ]
