# Generated by Django 3.2.15 on 2024-12-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_policeassureur_type_compagnie'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquepolice',
            name='garantie',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('', 'Choisir')], max_length=3, null=True),
        ),
    ]
