# Generated by Django 3.2.15 on 2024-12-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_typecompagnie'),
        ('production', '0022_historiquepolice_garantie'),
    ]

    operations = [
        migrations.AddField(
            model_name='policegarantie',
            name='formule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.formule'),
        ),
    ]
