# Generated by Django 3.2.15 on 2023-08-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0035_typeclient_code'),
        ('production', '0022_auto_20230808_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='fractionnement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.fractionnement'),
        ),
        migrations.AlterField(
            model_name='police',
            name='mode_reglement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.modereglement'),
        ),
        migrations.AlterField(
            model_name='police',
            name='regularisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.regularisation'),
        ),
    ]
