# Generated by Django 3.2.15 on 2023-08-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0044_auto_20230817_0905'),
        ('production', '0023_auto_20230808_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='bareme',
            name='plafond_regroupement_acte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bareme',
            name='plafond_sous_rubrique',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bareme',
            name='regroupement_acte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.regroupementacte'),
        ),
        migrations.AddField(
            model_name='bareme',
            name='sous_rubrique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.sousrubrique'),
        ),
    ]
