# Generated by Django 3.2.15 on 2023-09-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_auto_20230817_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='veos_id_pol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
