# Generated by Django 3.2.15 on 2024-12-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_alter_historiquepolice_garantie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquepolice',
            name='garantie',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
