# Generated by Django 3.2.15 on 2023-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_police_veos_id_pol'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='veos_adherent_principal_id_per',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='veos_assure_sante_idper',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='veos_client_idper',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
