# Generated by Django 3.2.15 on 2024-12-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_alter_historiquepolice_garantie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquepolice',
            name='mode_renouvellement',
            field=models.CharField(choices=[('Tacite Reconduction', 'Tacite Reconduction'), ('Sans Tacite Reconduction', 'Sans Tacite Reconduction'), ('', 'Choisir')], max_length=50, null=True),
        ),
    ]
