# Generated by Django 3.2.15 on 2024-12-22 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_conditionsassurance_moyenstransport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0027_alter_historiquepolice_mode_renouvellement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_certificat', models.CharField(blank=True, max_length=50, null=True)),
                ('num_fact_fournisseur', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_dai', models.CharField(blank=True, max_length=50, null=True)),
                ('date_commande', models.DateField(null=True)),
                ('nombre_colis', models.CharField(blank=True, max_length=100, null=True)),
                ('poids_brut', models.CharField(blank=True, max_length=100, null=True)),
                ('plein_souscription', models.CharField(blank=True, max_length=100, null=True)),
                ('immatriculation', models.CharField(blank=True, max_length=100, null=True)),
                ('pavillon_cie_prest', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('lieu_transit_transbordement', models.CharField(blank=True, max_length=100, null=True)),
                ('date_emmision_certificat', models.DateField(null=True)),
                ('date_sortie', models.DateField(null=True)),
                ('num_commande', models.CharField(blank=True, max_length=100, null=True)),
                ('marchandises_description', models.TextField(null=True)),
                ('poids_net', models.CharField(blank=True, max_length=100, null=True)),
                ('valeur_assuree', models.FloatField(null=True)),
                ('marque_modele_type', models.CharField(blank=True, max_length=100, null=True)),
                ('debut_voyage', models.DateField(null=True)),
                ('lieu_depart', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('courriel', models.CharField(blank=True, max_length=100, null=True)),
                ('taux_risque_ordinaire', models.FloatField(null=True)),
                ('taux_risque_guerre', models.FloatField(null=True)),
                ('taux_supprime', models.FloatField(null=True)),
                ('taux_taxe', models.FloatField(null=True)),
                ('accessoires', models.IntegerField(blank=True, null=True)),
                ('autres_frais', models.IntegerField(blank=True, null=True)),
                ('prime_risque_ordinaire', models.BigIntegerField(null=True)),
                ('prime_risque_guerre', models.BigIntegerField(null=True)),
                ('prime_supprime', models.BigIntegerField(null=True)),
                ('prime_brut', models.BigIntegerField(null=True)),
                ('total_taxe', models.BigIntegerField(null=True)),
                ('prime_ttc_mar', models.BigIntegerField(null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ANNULE', 'Annule')], default='ACTIF', max_length=15, null=True)),
                ('date_du_jour', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conditions_assurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.conditionsassurance')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('devise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.devise')),
                ('moyens_transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.moyenstransport')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='marchandise_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marchandises',
                'verbose_name_plural': 'Marchandises',
                'db_table': 'marchandises',
            },
        ),
        migrations.AddField(
            model_name='alimentpolice',
            name='marchandise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.marchandise'),
        ),
    ]
