# Generated by Django 3.2.15 on 2023-10-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_aliment_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='observation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
