# Generated by Django 3.2.15 on 2024-12-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_auto_20241222_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchandise',
            name='date_du_jour',
        ),
        migrations.AddField(
            model_name='marchandise',
            name='date_liaison',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
