# Generated by Django 3.2.15 on 2024-12-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_auto_20241222_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='date_fin_effet',
            field=models.DateField(null=True),
        ),
    ]
