# Generated by Django 3.2.15 on 2023-10-27 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0031_alter_alimentformule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='polices', to='production.client'),
        ),
    ]
