# Generated by Django 3.2.15 on 2024-12-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0032_police_date_debut_effet'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchandise',
            name='taux_reduction_commerciale',
            field=models.FloatField(null=True),
        ),
    ]
