# Generated by Django 3.2.15 on 2024-12-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0033_marchandise_taux_reduction_commerciale'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchandise',
            name='prime_reduction',
            field=models.BigIntegerField(null=True),
        ),
    ]
