# Generated by Django 3.2.15 on 2023-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0034_auto_20231103_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='etat',
            field=models.CharField(choices=[('ENTRÉ', 'Entre'), ('SUSPENDU', 'Suspendu'), ('SORTIE', 'Sortie')], default=None, max_length=15, null=True),
        ),
    ]
