# Generated by Django 3.2.15 on 2024-12-25 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0035_historiquealiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiquealiment',
            old_name='marchandises',
            new_name='marchandise',
        ),
    ]
