# Generated by Django 4.0.3 on 2023-11-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0035_aliment_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliment',
            name='etat',
        ),
    ]
