# Generated by Django 3.2.15 on 2024-12-26 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_conditionsassurance_moyenstransport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0036_rename_marchandises_historiquealiment_marchandise'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquealiment',
            name='carburant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.carburant'),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='carosserie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.carosserie'),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='categorie_vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.categorievehicule'),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='commentaire',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='conducteur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='date_entree',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='date_mis_en_circulation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='existed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='histo_aliment_existed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='marque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='modele',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='numero_immat_provisoire',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='numero_immatriculation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='numero_parc',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='places_assises',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='poids_a_charge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='poids_a_vide',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='proprietaire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='puissance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.usage'),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='valeur_actuelle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='valeur_neuve',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiquealiment',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.vehicule'),
        ),
        migrations.DeleteModel(
            name='HistoriqueVehicule',
        ),
    ]
