# Generated by Django 3.2.15 on 2023-11-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0036_remove_aliment_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fichier',
        ),
    ]
