# Generated by Django 3.2.15 on 2023-11-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0037_remove_document_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, default=None, null=True, upload_to='clients/documents'),
        ),
    ]
