# Generated by Django 3.2.15 on 2024-12-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0038_autrerisque_date_liaison'),
    ]

    operations = [
        migrations.AddField(
            model_name='autrerisque',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ANNULE', 'Annule')], default='ACTIF', max_length=15, null=True),
        ),
    ]
