# Generated by Django 3.2.15 on 2024-12-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0039_autrerisque_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentpolice',
            name='autre_risque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.autrerisque'),
        ),
    ]
