# Generated by Django 3.2.15 on 2025-01-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0040_alimentpolice_autre_risque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acompte',
            old_name='montant',
            new_name='credit',
        ),
        migrations.AddField(
            model_name='acompte',
            name='debit',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
