# Generated by Django 3.2.15 on 2023-12-08 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0040_alter_client_code_provisoire'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_import', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_famille_import', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.aliment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aliment temporaire',
                'verbose_name_plural': 'Aliments temporaires',
                'db_table': 'aliment_temporaire',
            },
        ),
    ]
