# Generated by Django 3.2.15 on 2025-01-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0041_auto_20250102_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompte',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='acompte',
            name='sens',
        ),
        migrations.AddField(
            model_name='acompte',
            name='periode_debut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='acompte',
            name='periode_fin',
            field=models.DateField(null=True),
        ),
    ]
