# Generated by Django 3.2.15 on 2023-12-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0041_alimenttemporaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='sms_active',
            field=models.BooleanField(default=False),
        ),
    ]
