# Generated by Django 3.2.15 on 2025-01-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0042_auto_20250103_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompte',
            name='solde',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
