# Generated by Django 3.2.15 on 2023-12-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0046_aliment_apci_ald'),
    ]

    operations = [
        migrations.AddField(
            model_name='motif',
            name='etat_police',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
