# Generated by Django 3.2.15 on 2023-12-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0047_motif_etat_police'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='taux_com_courtage_terme',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='taux_com_courtage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='taux_com_gestion',
            field=models.FloatField(null=True),
        ),
    ]
