# Generated by Django 3.2.15 on 2023-12-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0049_alter_police_logo_partenaire'),
        ('production', '0049_alter_quittance_numero'),
    ]

    operations = [
    ]
