# Generated by Django 3.2.15 on 2023-12-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0052_alimentformule_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentformule',
            name='aliment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='historique_formules', to='production.aliment'),
        ),
    ]
