# Generated by Django 3.2.15 on 2024-01-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0127_apporteur_bureau'),
        ('production', '0054_mouvementpolice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulegarantie',
            name='reseau_soin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.reseausoin'),
        ),
    ]
