# Generated by Django 4.0.3 on 2024-01-04 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0055_formulegarantie_reseau_soin'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='user_extranet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
