# Generated by Django 3.2.15 on 2024-01-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0056_auto_20240109_1128'),
        ('production', '0056_mouvementaliment'),
    ]

    operations = [
    ]
