# Generated by Django 3.2.15 on 2024-01-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0058_auto_20240111_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementaliment',
            options={'verbose_name': "Mouvement sur l'aliment", 'verbose_name_plural': "Mouvements sur l'aliment"},
        ),
        migrations.AlterModelTable(
            name='mouvementaliment',
            table='mouvements_aliments',
        ),
    ]
