# Generated by Django 3.2.15 on 2024-01-11 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0059_auto_20240111_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementaliment',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementaliment',
            name='aliment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ses_mouvements', to='production.aliment'),
        ),
    ]
