# Generated by Django 3.2.15 on 2024-01-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0060_auto_20240111_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoIdentite',
        ),
    ]
