# Generated by Django 3.2.15 on 2024-01-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0061_delete_photoidentite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementaliment',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police'),
        ),
    ]
