# Generated by Django 3.2.15 on 2024-01-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0064_aliment_numero_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='numero_famille_v1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
