# Generated by Django 3.2.15 on 2024-01-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0056_aliment_user_extranet'),
        ('production', '0065_aliment_numero_famille_v1'),
    ]

    operations = [
    ]
