# Generated by Django 3.2.15 on 2024-01-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0066_merge_20240119_1144'),
        ('production', '0067_alter_aliment_user_extranet'),
    ]

    operations = [
    ]
