# Generated by Django 4.0.3 on 2024-01-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0068_merge_20240123_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='numero_famille_du_mois',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
