# Generated by Django 3.2.15 on 2024-01-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0069_aliment_numero_famille_du_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulegarantie',
            name='infos_carte_show_numero_police',
            field=models.BooleanField(default=True),
        ),
    ]
