# Generated by Django 3.2.15 on 2024-01-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0070_formulegarantie_infos_carte_show_numero_police'),
    ]

    operations = [
        migrations.AddField(
            model_name='quittance',
            name='taux_com_courtage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quittance',
            name='taux_com_gestion',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
