# Generated by Django 3.2.15 on 2024-01-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0071_auto_20240130_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='numero_piece',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
