# Generated by Django 3.2.15 on 2024-02-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0075_apporteurpolice_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglement',
            name='quittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ses_quittances', related_query_name='quittance', to='production.quittance'),
        ),
    ]
