# Generated by Django 3.2.15 on 2024-02-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0153_natureoperation_code'),
        ('production', '0077_auto_20240210_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='compte_tresorerie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.comptetresorerie'),
        ),
        migrations.AddField(
            model_name='operation',
            name='numero_piece',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
