# Generated by Django 3.2.15 on 2024-02-13 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0078_auto_20240213_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut_validite', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.operation')),
                ('reglement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.reglement')),
            ],
            options={
                'verbose_name': 'Opération sur un règlement',
                'verbose_name_plural': 'Opérations sur les règlements',
                'db_table': 'operation_reglement',
            },
        ),
    ]
