# Generated by Django 3.2.15 on 2024-02-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0079_operationreglement'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentformule',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alimentformule',
            name='statut_validite',
            field=models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='VALIDE', max_length=15, null=True),
        ),
    ]
