# Generated by Django 3.2.15 on 2024-02-27 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0080_auto_20240221_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.client')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
            ],
            options={
                'verbose_name': 'Client police',
                'verbose_name_plural': 'Clients-polices',
                'db_table': 'client_police',
            },
        ),
    ]
