# Generated by Django 3.2.15 on 2024-03-05 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0081_policeclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementpolice',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mouvementpolice',
            name='mp_deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mp_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouvementpolice',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mouvementpolice',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True),
        ),
    ]
