# Generated by Django 3.2.15 on 2024-03-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0083_aliment_statut_incorporation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementaliment',
            name='statut_traitement',
            field=models.CharField(choices=[('TRAITE', 'Traite'), ('NON TRAITE', 'Non Traite')], default='TRAITE', max_length=15, null=True),
        ),
    ]
