# Generated by Django 3.2.15 on 2024-03-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0084_mouvementaliment_statut_traitement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='motif_annulation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reglement',
            name='observation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reglement',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True),
        ),
    ]
