# Generated by Django 3.2.15 on 2024-03-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0085_auto_20240325_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='date_encaissement_commission',
            field=models.DateTimeField(null=True),
        ),
    ]
