# Generated by Django 3.2.15 on 2024-04-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0086_reglement_date_encaissement_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='fichier',
            field=models.FileField(blank=True, default=None, null=True, upload_to='bordereaux/'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
