# Generated by Django 3.2.15 on 2024-04-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0087_auto_20240416_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True),
        ),
    ]
