# Generated by Django 3.2.15 on 2024-05-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0088_police_statut_validite'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodecouverture',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='periodecouverture',
            name='statut_validite',
            field=models.CharField(blank=True, choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True),
        ),
    ]
