# Generated by Django 3.2.15 on 2024-05-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0089_auto_20240501_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='has_photo_veos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aliment',
            name='statut_import_photo_veos',
            field=models.BooleanField(default=False),
        ),
    ]
