# Generated by Django 3.2.15 on 2024-05-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0090_auto_20240508_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photos/'),
        ),
    ]
