# Generated by Django 3.2.15 on 2024-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0091_alter_aliment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='banque_emettrice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
