# Generated by Django 3.2.15 on 2024-05-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0172_changementformule_sousregroupementacte_sousregroupementacteacte'),
        ('production', '0092_operation_banque_emettrice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bareme',
            name='plafond_sous_regroupement_acte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bareme',
            name='sous_regroupement_acte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.sousregroupementacte'),
        ),
    ]
