# Generated by Django 3.2.15 on 2024-05-28 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0174_merge_20240527_1052'),
        ('production', '0093_auto_20240524_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormuleRubriquePrefinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut_validite', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('formulegarantie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.formulegarantie')),
                ('rubrique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.rubrique')),
            ],
            options={
                'verbose_name': 'Rubrique préfinancé sur la formule',
                'verbose_name_plural': 'Rubriques préfinancés sur la formule',
                'db_table': 'formule_rubrique_prefinance',
            },
        ),
    ]
