# Generated by Django 3.2.15 on 2024-05-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0094_formulerubriqueprefinance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModePrefinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mode de prefinancement',
                'verbose_name_plural': 'Modes de prefinancement',
                'db_table': 'mode_prefinancement',
            },
        ),
        migrations.AddField(
            model_name='formulegarantie',
            name='mode_prefinancement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.modeprefinancement'),
        ),
    ]
