# Generated by Django 3.2.15 on 2024-05-29 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0175_remove_compagnie_has_taux_multiple'),
        ('production', '0095_auto_20240528_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxCouvertureVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_couverture', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut_validite', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('formulegarantie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.formulegarantie')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.secteur')),
            ],
            options={
                'verbose_name': 'Taux de couverture',
                'verbose_name_plural': 'Taux de couverture',
                'db_table': 'taux_couverture_variable',
            },
        ),
    ]
