# Generated by Django 3.2.15 on 2024-05-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0176_bureau_option_assurance_universelle'),
        ('production', '0095_auto_20240528_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulegarantie',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau'),
        ),
    ]
