# Generated by Django 3.2.15 on 2024-05-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0096_formulegarantie_bureau'),
        ('production', '0096_tauxcouverturevariable'),
    ]

    operations = [
    ]
