# Generated by Django 3.2.15 on 2024-06-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0096_tauxcouverturevariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='observation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True),
        ),
    ]
