# Generated by Django 5.0.6 on 2024-06-06 11:16

import production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0096_tauxcouverturevariable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="fichier",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=production.models.upload_location_document,
            ),
        ),
    ]
