# Generated by Django 3.2.15 on 2024-06-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0097_alter_document_fichier'),
        ('production', '0097_auto_20240607_1055'),
    ]

    operations = [
    ]
