# Generated by Django 3.2.15 on 2024-06-08 12:17

from django.db import migrations, models
import production.models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0098_merge_20240607_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=production.models.upload_location_aliment),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=production.models.upload_location_client),
        ),
        migrations.AlterField(
            model_name='operation',
            name='fichier',
            field=models.FileField(blank=True, default=None, null=True, upload_to=production.models.upload_location_operation),
        ),
        migrations.AlterField(
            model_name='tarifprestataireclient',
            name='fichier_tarification',
            field=models.FileField(blank=True, default=None, null=True, upload_to=production.models.upload_location_tarifprestataireclient),
        ),
    ]
