# Generated by Django 3.2.15 on 2024-06-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0097_merge_20240531_1446'),
        ('production', '0099_auto_20240608_1217'),
    ]

    operations = [
    ]
