# Generated by Django 3.2.15 on 2024-06-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0100_merge_20240611_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='uuid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
