# Generated by Django 3.2.15 on 2024-06-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0099_auto_20240607_1455'),
        ('production', '0101_operation_uuid'),
    ]

    operations = [
    ]
