# Generated by Django 3.2.15 on 2024-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0103_alter_police_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apporteurpolice',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='apporteurpolice',
            name='statut_validite',
            field=models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='VALIDE', max_length=15, null=True),
        ),
    ]
