# Generated by Django 5.0.6 on 2024-06-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0103_alter_police_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulegarantie",
            name="exclusion",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
