# Generated by Django 3.2.15 on 2024-07-02 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0105_client_groupe_international'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='police_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
