# Generated by Django 3.2.15 on 2024-07-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0104_formulegarantie_exclusion'),
        ('production', '0105_client_groupe_international'),
    ]

    operations = [
    ]
