# Generated by Django 3.2.15 on 2024-07-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0106_police_updated_by'),
        ('production', '0107_auto_20240703_1036'),
    ]

    operations = [
    ]
