# Generated by Django 5.0.7 on 2024-07-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0106_merge_20240704_1501"),
        ("production", "0108_merge_0106_police_updated_by_0107_auto_20240703_1036"),
    ]

    operations = []
