# Generated by Django 3.2.15 on 2024-07-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0106_merge_20240704_1501'),
        ('production', '0108_merge_0106_police_updated_by_0107_auto_20240703_1036'),
    ]

    operations = [
    ]
