# Generated by Django 3.2.15 on 2024-07-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0109_merge_20240710_1059'),
        ('production', '0109_merge_20240712_1608'),
        ('production', '0109_merge_20240715_1328'),
    ]

    operations = [
    ]
