# Generated by Django 3.2.15 on 2024-07-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0106_merge_20240704_1213'),
        ('production', '0109_merge_20240705_1051'),
        ('production', '0109_merge_20240715_1328'),
    ]

    operations = [
    ]
