# Generated by Django 3.2.15 on 2024-07-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0106_merge_20240704_1213'),
        ('production', '0109_merge_20240705_1012'),
    ]

    operations = [
    ]
