# Generated by Django 5.0.7 on 2024-07-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0109_merge_20240710_1059"),
        ("production", "0109_merge_20240712_1608"),
        ("production", "0109_merge_20240715_1328"),
        ("production", "0110_merge_20240711_1803"),
    ]

    operations = []
