# Generated by Django 3.2.15 on 2024-07-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0110_merge_20240716_1524'),
        ('production', '0111_merge_20240724_0957'),
    ]

    operations = [
    ]
