# Generated by Django 3.2.15 on 2024-07-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0110_merge_20240711_1803'),
        ('production', '0111_merge_20240722_0819'),
    ]

    operations = [
    ]
