# Generated by Django 3.2.15 on 2024-07-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0110_merge_20240722_1301'),
        ('production', '0112_merge_20240726_1027'),
    ]

    operations = [
    ]
