# Generated by Django 3.2.15 on 2024-08-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0109_merge_20240711_1300'),
        ('production', '0110_document_quittance'),
        ('production', '0110_merge_20240712_1619'),
        ('production', '0113_merge_20240726_1108'),
    ]

    operations = [
    ]
