# Generated by Django 3.2.15 on 2024-07-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0112_merge_20240722_1802'),
        ('production', '0113_merge_20240726_1108'),
    ]

    operations = [
    ]
