# Generated by Django 3.2.15 on 2024-08-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0110_merge_20240718_1707'),
        ('production', '0114_merge_20240808_1729'),
    ]

    operations = [
    ]
