# Generated by Django 3.2.15 on 2024-07-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0109_merge_20240711_1300'),
        ('production', '0114_merge_20240726_1141'),
    ]

    operations = [
    ]
