# Generated by Django 3.2.15 on 2024-07-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0110_document_quittance'),
        ('production', '0110_merge_20240712_1619'),
        ('production', '0115_merge_20240729_0923'),
    ]

    operations = [
    ]
