# Generated by Django 3.2.15 on 2024-08-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0114_merge_20240808_1729'),
        ('production', '0116_merge_20240730_1644'),
    ]

    operations = [
    ]
