# Generated by Django 3.2.15 on 2024-08-22 09:55

from django.db import migrations, models
import production.models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0116_merge_20240822_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='quittance',
            name='taux_euro',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='quittance',
            name='taux_usd',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='carte',
            name='qrcode_file',
            field=models.ImageField(blank=True, null=True, upload_to=production.models.upload_location_carte),
        ),
    ]
