# Generated by Django 3.2.15 on 2024-08-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0110_merge_20240726_1026'),
        ('production', '0114_merge_20240806_1656'),
        ('production', '0115_merge_20240821_1634'),
        ('production', '0117_merge_20240808_1734'),
    ]

    operations = [
    ]
