# Generated by Django 3.2.15 on 2024-08-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0117_auto_20240822_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittance',
            name='taux_euro',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='taux_usd',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
