# Generated by Django 3.2.15 on 2024-08-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0116_merge_20240822_0931'),
        ('production', '0118_merge_20240821_1732'),
    ]

    operations = [
    ]
