# Generated by Django 3.2.15 on 2024-09-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0114_merge_20240730_1641'),
        ('production', '0118_auto_20240822_0957'),
    ]

    operations = [
    ]
