# Generated by Django 3.2.15 on 2024-08-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('production', '0118_alter_carte_qrcode_file'),
        ('production', '0118_auto_20240822_0957'),
    ]

    operations = [
    ]
