# Generated by Django 3.2.15 on 2024-09-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0119_merge_20240828_1839'),
        ('production', '0120_merge_20240822_1001'),
    ]

    operations = [
    ]
