# Generated by Django 3.2.15 on 2024-09-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0119_merge_20240909_1413'),
        ('production', '0121_merge_20240903_2157'),
    ]

    operations = [
    ]
