# Generated by Django 3.2.15 on 2024-09-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0218_periodeveos'),
        ('production', '0122_merge_20240912_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau'),
        ),
    ]
