# Generated by Django 3.2.15 on 2024-09-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0123_carte_bureau'),
    ]

    operations = [
        migrations.AddField(
            model_name='quittance',
            name='import_stats',
            field=models.BooleanField(default=False),
        ),
    ]
