# Generated by Django 3.2.15 on 2024-09-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0124_quittance_import_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittance',
            name='import_stats',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
