# Generated by Django 5.1.1 on 2024-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0125_alter_quittance_import_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="secteur_activite",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
