# Generated by Django 3.2.15 on 2024-09-25 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0126_client_secteur_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteDigitalDematerialisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_digital_card', models.BooleanField(default=False)),
                ('digital_card_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carte Digital Dématérialisée',
                'verbose_name_plural': 'Cartes Digital Dématérialisées',
                'db_table': 'cartes_digital_dematerialisees',
            },
        ),
    ]
