# Generated by Django 3.2.15 on 2024-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0127_cartedigitaldematerialisee'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='profession_libelle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
