# Generated by Django 3.2.15 on 2024-10-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0128_reglement_banque_emettrice'),
        ('production', '0129_auto_20241009_1023'),
    ]

    operations = [
    ]
