# Generated by Django 3.2.15 on 2024-10-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0111_merge_20240724_1158'),
        ('production', '0130_merge_20241009_1031'),
    ]

    operations = [
    ]
