# Generated by Django 3.2.15 on 2024-10-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0131_merge_20241010_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='etat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
