# Generated by Django 3.2.15 on 2024-10-23 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0132_aliment_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompte',
            name='reste',
        ),
        migrations.AddField(
            model_name='acompte',
            name='date_affectation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acompte',
            name='libelle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acompte',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acompte',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police'),
        ),
        migrations.AddField(
            model_name='acompte',
            name='quittance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.quittance'),
        ),
        migrations.AddField(
            model_name='acompte',
            name='sens',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='acompte',
            name='date_versement',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='acompte',
            name='montant',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
