# Generated by Django 3.2.15 on 2024-10-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0133_auto_20241023_1100"),
    ]

    operations = [
        #   migrations.AddField(
        #       model_name='mouvementpolice',
        #       name='historique_police',
        #       field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.historiquepolice'),
        #   ),
    ]
