# Generated by Django 3.2.15 on 2024-10-31 17:10
# Generated by Django 4.2.14 on 2024-11-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0134_mouvementpolice_historique_police'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementpolice',
            name='historique_police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.historiquepolice'),
        ),
    ]
