# Generated by Django 4.2.14 on 2024-11-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0135_mouvementpolice_historique_police'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='secteur_activite',
        ),
    ]
