# Generated by Django 4.2.14 on 2024-11-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0136_remove_client_secteur_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecteurActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='secteur_activite',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.secteuractivite'),
        ),
    ]
