# Generated by Django 4.2.14 on 2024-11-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0137_secteuractivite_client_secteur_activite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secteuractivite',
            old_name='created_by',
            new_name='created_at',
        ),
    ]
