# Generated by Django 3.2.15 on 2024-11-25 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0229_auto_20241125_1633'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0138_rename_created_by_secteuractivite_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secteuractivite',
            options={'verbose_name': "Secteur d'activité ", 'verbose_name_plural': "Secteur d'activité"},
        ),
        migrations.AddField(
            model_name='client',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.businessunit'),
        ),
        migrations.AlterField(
            model_name='acompte',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.client'),
        ),
        migrations.AlterField(
            model_name='acompte',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='acompte',
            name='quittance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.quittance'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='adherent_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.aliment'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.bureau'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='civilite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.civilite'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='pays_activite_professionnelle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pays_activite_professionnelle', to='configurations.pays'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='pays_naissance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pays_naissance', to='configurations.pays'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='pays_residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pays_residence', to='configurations.pays'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.profession'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='qualite_beneficiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.qualitebeneficiaire'),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='user_extranet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alimentformule',
            name='aliment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_formules', to='production.aliment'),
        ),
        migrations.AlterField(
            model_name='alimentformule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alimentformule',
            name='formule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.formulegarantie'),
        ),
        migrations.AlterField(
            model_name='alimenttemporaire',
            name='aliment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.aliment'),
        ),
        migrations.AlterField(
            model_name='alimenttemporaire',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apporteurpolice',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apporteurpolice',
            name='apporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.apporteur'),
        ),
        migrations.AlterField(
            model_name='apporteurpolice',
            name='base_calcul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.basecalcul'),
        ),
        migrations.AlterField(
            model_name='apporteurpolice',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='acte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.acte'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='formulegarantie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.formulegarantie'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='periodicite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.periodicite'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='qualite_beneficiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.qualitebeneficiaire'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='regroupement_acte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.regroupementacte'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='rubrique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.rubrique'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='sous_regroupement_acte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.sousregroupementacte'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='sous_rubrique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.sousrubrique'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='aliment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartes', to='production.aliment'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.bureau'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bureau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.bureau'),
        ),
        migrations.AlterField(
            model_name='client',
            name='civilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.civilite'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='gestionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestionnaire_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='groupe_international',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.groupeinter'),
        ),
        migrations.AlterField(
            model_name='client',
            name='langue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.langue'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.pays'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.typeclient'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_personne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.typepersonne'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.client'),
        ),
        migrations.AlterField(
            model_name='document',
            name='aliment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.aliment'),
        ),
        migrations.AlterField(
            model_name='document',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.client'),
        ),
        migrations.AlterField(
            model_name='document',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='document',
            name='quittance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.quittance'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.typedocument'),
        ),
        migrations.AlterField(
            model_name='filiale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.client'),
        ),
        migrations.AlterField(
            model_name='filiale',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.pays'),
        ),
        migrations.AlterField(
            model_name='formulegarantie',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.bureau'),
        ),
        migrations.AlterField(
            model_name='formulegarantie',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formulegarantie',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fg_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formulegarantie',
            name='mode_prefinancement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.modeprefinancement'),
        ),
        migrations.AlterField(
            model_name='formulegarantie',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='formulegarantie',
            name='reseau_soin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.reseausoin'),
        ),
        migrations.AlterField(
            model_name='formulegarantie',
            name='territorialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.territorialite'),
        ),
        migrations.AlterField(
            model_name='formulegarantie',
            name='type_tarif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.typetarif'),
        ),
        migrations.AlterField(
            model_name='formulegarantie',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fg_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formulerubriqueprefinance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formulerubriqueprefinance',
            name='formulegarantie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.formulegarantie'),
        ),
        migrations.AlterField(
            model_name='formulerubriqueprefinance',
            name='rubrique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.rubrique'),
        ),
        migrations.AlterField(
            model_name='historiqueapporteurpolice',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiqueapporteurpolice',
            name='apporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.apporteur'),
        ),
        migrations.AlterField(
            model_name='historiqueapporteurpolice',
            name='base_calcul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.basecalcul'),
        ),
        migrations.AlterField(
            model_name='historiqueapporteurpolice',
            name='historique_police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.historiquepolice'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='bureau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.bureau'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.client'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.compagnie'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='devise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.devise'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='fractionnement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.fractionnement'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='mode_calcul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.modecalcul'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='mode_reglement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.modereglement'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.produit'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='regularisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.regularisation'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='ticket_moderateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.ticketmoderateur'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='type_assurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.typeassurance'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='type_prefinancement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.typeprefinancement'),
        ),
        migrations.AlterField(
            model_name='historiquepolice',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_police_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiquetaxepolice',
            name='historique_police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.historiquepolice'),
        ),
        migrations.AlterField(
            model_name='historiquetaxepolice',
            name='taxe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.taxe'),
        ),
        migrations.AlterField(
            model_name='motif',
            name='mouvement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvementaliment',
            name='aliment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ses_mouvements', to='production.aliment'),
        ),
        migrations.AlterField(
            model_name='mouvementaliment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mouvementaliment',
            name='mouvement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvementaliment',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='mouvementpolice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mouvementpolice',
            name='historique_police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.historiquepolice'),
        ),
        migrations.AlterField(
            model_name='mouvementpolice',
            name='motif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.motif'),
        ),
        migrations.AlterField(
            model_name='mouvementpolice',
            name='mouvement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvementpolice',
            name='mp_deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mouvementpolice',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='mouvementquittance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mouvementquittance',
            name='mouvement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvementquittance',
            name='quittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.quittance'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='banque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.banque'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='compte_tresorerie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.comptetresorerie'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='mode_reglement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.modereglement'),
        ),
        migrations.AlterField(
            model_name='operationreglement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operationreglement',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.operation'),
        ),
        migrations.AlterField(
            model_name='operationreglement',
            name='reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.reglement'),
        ),
        migrations.AlterField(
            model_name='periodecouverture',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='photoidentite',
            name='aliment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.aliment'),
        ),
        migrations.AlterField(
            model_name='police',
            name='bureau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.bureau'),
        ),
        migrations.AlterField(
            model_name='police',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polices', to='production.client'),
        ),
        migrations.AlterField(
            model_name='police',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.compagnie'),
        ),
        migrations.AlterField(
            model_name='police',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='police',
            name='devise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.devise'),
        ),
        migrations.AlterField(
            model_name='police',
            name='fractionnement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.fractionnement'),
        ),
        migrations.AlterField(
            model_name='police',
            name='mode_calcul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.modecalcul'),
        ),
        migrations.AlterField(
            model_name='police',
            name='mode_reglement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.modereglement'),
        ),
        migrations.AlterField(
            model_name='police',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.produit'),
        ),
        migrations.AlterField(
            model_name='police',
            name='regularisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.regularisation'),
        ),
        migrations.AlterField(
            model_name='police',
            name='ticket_moderateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.ticketmoderateur'),
        ),
        migrations.AlterField(
            model_name='police',
            name='type_assurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.typeassurance'),
        ),
        migrations.AlterField(
            model_name='police',
            name='type_prefinancement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.typeprefinancement'),
        ),
        migrations.AlterField(
            model_name='police',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policeclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.client'),
        ),
        migrations.AlterField(
            model_name='policeclient',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.bureau'),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='compagnie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.compagnie'),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quittance_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='devise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.devise'),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='nature_quittance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.naturequittance'),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='type_quittance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.typequittance'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='banque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.banque'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.bureau'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='compagnie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglements', related_query_name='reglement', to='configurations.compagnie'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='compte_tresorerie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.comptetresorerie'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='mode_reglement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.modereglement'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='quittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ses_quittances', related_query_name='quittance', to='production.quittance'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='reg_deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarifprestataireclient',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.client'),
        ),
        migrations.AlterField(
            model_name='tarifprestataireclient',
            name='formule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.formulegarantie'),
        ),
        migrations.AlterField(
            model_name='tarifprestataireclient',
            name='prestataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.prestataire'),
        ),
        migrations.AlterField(
            model_name='tauxcouverturevariable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tauxcouverturevariable',
            name='formulegarantie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.formulegarantie'),
        ),
        migrations.AlterField(
            model_name='tauxcouverturevariable',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.secteur'),
        ),
        migrations.AlterField(
            model_name='taxepolice',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='taxepolice',
            name='taxe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.taxe'),
        ),
        migrations.AlterField(
            model_name='taxequittance',
            name='quittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.quittance'),
        ),
        migrations.AlterField(
            model_name='taxequittance',
            name='taxe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.taxe'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='categorie_vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.categorievehicule'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.marquevehicule'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_carosserie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.typecarosserie'),
        ),
        migrations.AlterField(
            model_name='vehiculepolice',
            name='formule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.formulegarantie'),
        ),
        migrations.AlterField(
            model_name='vehiculepolice',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.police'),
        ),
        migrations.AlterField(
            model_name='vehiculepolice',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.vehicule'),
        ),
        migrations.AlterModelTable(
            name='secteuractivite',
            table='secteur_activite',
        ),
    ]
