# Generated by Django 3.2.15 on 2024-01-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='code',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
