# Generated by Django 3.2.15 on 2024-02-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0002_alter_campagne_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
