# Generated by Django 3.2.15 on 2024-02-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0003_auto_20240205_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='prospects/'),
        ),
    ]
