# Generated by Django 3.2.15 on 2024-02-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0004_alter_prospect_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagneprospect',
            name='statut_enrolement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('EN COURS', 'Encours'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete')], default='EN ATTENTE', max_length=15, null=True),
        ),
    ]
