# Generated by Django 3.2.15 on 2024-02-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0007_auto_20240228_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='statut_enrolement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('EN COURS', 'Encours'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete')], default='EN ATTENTE', max_length=15, null=True),
        ),
    ]
