# Generated by Django 3.2.15 on 2024-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0008_prospect_statut_enrolement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagneprospect',
            name='statut_enrolement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('EN COURS', 'Encours'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete'), ('INCORPORE', 'Incorpore')], default='EN ATTENTE', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='statut_enrolement',
            field=models.CharField(choices=[('EN ATTENTE', 'Attente'), ('EN COURS', 'Encours'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete'), ('INCORPORE', 'Incorpore')], default='EN ATTENTE', max_length=15, null=True),
        ),
    ]
