# Generated by Django 3.2.15 on 2024-03-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0081_policeclient'),
        ('grh', '0009_auto_20240304_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='aliment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.aliment'),
        ),
    ]
