# Generated by Django 3.2.15 on 2024-03-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0082_auto_20240305_1627'),
        ('grh', '0010_prospect_aliment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='aliment_adherent_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='aliment_adherent_principal', to='production.aliment'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='aliment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.aliment'),
        ),
    ]
