# Generated by Django 3.2.15 on 2024-07-31 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0110_merge_20240726_1026'),
        ('grh', '0011_auto_20240307_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolementAppMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=25, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('adherent_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='grh.enrolementappmobile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('formulegarantie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.formulegarantie')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
            ],
            options={
                'verbose_name': 'Enrolement_App_Mobile',
                'verbose_name_plural': 'enrolement_app_mobile',
                'db_table': 'enrolement_app_mobile',
            },
        ),
        migrations.CreateModel(
            name='EnrolementProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=255, null=True)),
                ('uiid', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('statut_enrolement', models.CharField(choices=[('EN ATTENTE', 'Attente'), ('EN COURS', 'Encours'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete'), ('INCORPORE', 'Incorpore')], default='EN ATTENTE', max_length=15, null=True)),
                ('enrolement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='grh.enrolementappmobile')),
                ('prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='grh.prospect')),
            ],
        ),
    ]
