# Generated by Django 3.2.15 on 2024-08-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0013_auto_20240801_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagneappmobileprospect',
            name='lien',
        ),
        migrations.RemoveField(
            model_name='campagneappmobileprospect',
            name='uiid',
        ),
    ]
