# Generated by Django 3.2.15 on 2024-08-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0014_auto_20240822_0955'),
        #('grh', '0015_auto_20240821_1838'),
    ]

    operations = [
    ]
