# Generated by Django 3.2.19 on 2023-06-17 13:28

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apporteur',
                'verbose_name_plural': 'Apporteurs',
                'db_table': 'apporteurs',
            },
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banque',
                'verbose_name_plural': 'Banques',
                'db_table': 'banques',
            },
        ),
        migrations.CreateModel(
            name='BaseCalcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base de calcul',
                'verbose_name_plural': 'Bases de calcul',
                'db_table': 'base_calculs',
            },
        ),
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branche',
                'verbose_name_plural': 'Branches',
                'db_table': 'branche',
            },
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('addresse', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('situation_geographique', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('tarfile', models.FileField(blank=True, default=None, null=True, upload_to='bureaux/tarifs')),
                ('cachet', models.ImageField(blank=True, default='', upload_to='bureaux/cachets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureaux',
                'db_table': 'bureau',
            },
        ),
        migrations.CreateModel(
            name='CategorieAffection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Categorie d'affection",
                'verbose_name_plural': "Categories d'affection",
                'db_table': 'categorie_affection',
            },
        ),
        migrations.CreateModel(
            name='CategorieVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de véhicule',
                'verbose_name_plural': 'Catégories de véhicule',
                'db_table': 'categorie_vehicule',
            },
        ),
        migrations.CreateModel(
            name='Civilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Civilite',
                'verbose_name_plural': 'Civilites',
                'db_table': 'civilites',
            },
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('addresse', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('taux_com_gestion', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('taux_com_courtage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
            ],
            options={
                'verbose_name': 'Compagnie',
                'verbose_name_plural': 'Compagnies',
                'db_table': 'compagnies',
            },
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'devises',
                'db_table': 'devises',
            },
        ),
        migrations.CreateModel(
            name='Duree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_mois', models.IntegerField(blank=True, null=True)),
                ('nombre_jours', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Durée',
                'verbose_name_plural': 'Durées',
                'db_table': 'durees',
            },
        ),
        migrations.CreateModel(
            name='Fractionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fractionnement',
                'verbose_name_plural': 'Fractionnements',
                'db_table': 'fractionnements',
            },
        ),
        migrations.CreateModel(
            name='Garantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Garantie',
                'verbose_name_plural': 'Garanties',
                'db_table': 'garanties',
            },
        ),
        migrations.CreateModel(
            name='GroupeInter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'GroupeInter',
                'verbose_name_plural': 'GroupeInters',
                'db_table': 'groupe_inters',
            },
        ),
        migrations.CreateModel(
            name='GroupeNat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'GroupeNat',
                'verbose_name_plural': 'GroupeNats',
                'db_table': 'groupe_nats',
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'db_table': 'langues',
            },
        ),
        migrations.CreateModel(
            name='MarqueVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'db_table': 'marque_vehicule',
            },
        ),
        migrations.CreateModel(
            name='ModeCalcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mode de calcul',
                'verbose_name_plural': 'Modes de calcul',
                'db_table': 'modes_calculs',
            },
        ),
        migrations.CreateModel(
            name='ModeReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mode de règlement',
                'verbose_name_plural': 'Modes de règlement',
                'db_table': 'mode_reglements',
            },
        ),
        migrations.CreateModel(
            name='NatureOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Nature de l'operation",
                'verbose_name_plural': 'Natures des operations',
                'db_table': 'nature_operations',
            },
        ),
        migrations.CreateModel(
            name='NatureQuittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nature de quittance',
                'verbose_name_plural': 'Natures de quittances',
                'db_table': 'nature_quittances',
            },
        ),
        migrations.CreateModel(
            name='Prescripteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenoms', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_ordre', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prescripteur',
                'verbose_name_plural': 'Prescripteurs',
                'db_table': 'prescripteur',
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('addresse', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to='prestataires/logos')),
                ('fichier_tarification', models.FileField(blank=True, default=None, null=True, upload_to='prestataires/tarifs')),
                ('liste_prescripteurs', models.FileField(blank=True, default=None, null=True, upload_to='prescripteurs/liste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
            ],
            options={
                'verbose_name': 'Prestataire',
                'verbose_name_plural': 'Prestataires',
                'db_table': 'prestataires',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='QualiteBeneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qualité bénéficiaire',
                'verbose_name_plural': 'Qualités bénéficiaire',
                'db_table': 'qualite_beneficiaire',
            },
        ),
        migrations.CreateModel(
            name='RegroupPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regroupement Personne',
                'verbose_name_plural': 'Regroupement Personnes',
                'db_table': 'regroup_personne',
            },
        ),
        migrations.CreateModel(
            name='Regularisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Régularisation',
                'verbose_name_plural': 'Régularisations',
                'db_table': 'regularisations',
            },
        ),
        migrations.CreateModel(
            name='ReseauSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Réseau de soins',
                'verbose_name_plural': 'Réseaux de soins',
                'db_table': 'reseaux_soins',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
                'db_table': 'secteur',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Specialite',
                'verbose_name_plural': 'Specialites',
                'db_table': 'specialities',
            },
        ),
        migrations.CreateModel(
            name='Taxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taxe',
                'verbose_name_plural': 'taxes',
                'db_table': 'taxes',
            },
        ),
        migrations.CreateModel(
            name='Territorialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Territorialites',
                'verbose_name_plural': 'Territorialites',
                'db_table': 'territorialites',
            },
        ),
        migrations.CreateModel(
            name='TicketModerateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket moderateur',
                'verbose_name_plural': 'Tickets moderateur',
                'db_table': 'ticket_moderateurs',
            },
        ),
        migrations.CreateModel(
            name='TypeAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type assurance',
                'verbose_name_plural': "Types d'assurance",
                'db_table': 'type_assurance',
            },
        ),
        migrations.CreateModel(
            name='TypeAssure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TypeAssure',
                'verbose_name_plural': 'TypeAssures',
                'db_table': 'type_assures',
            },
        ),
        migrations.CreateModel(
            name='TypeCarosserie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de carosserie',
                'verbose_name_plural': 'Types de carosserie',
                'db_table': 'type_carosserie',
            },
        ),
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de client',
                'verbose_name_plural': 'Types de client',
                'db_table': 'type_clients',
            },
        ),
        migrations.CreateModel(
            name='TypePersonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de personne',
                'verbose_name_plural': 'Types de personne',
                'db_table': 'type_personnes',
            },
        ),
        migrations.CreateModel(
            name='TypePrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de prestataire',
                'verbose_name_plural': 'Types de prestataires',
                'db_table': 'type_prestataires',
            },
        ),
        migrations.CreateModel(
            name='TypePriseencharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Types de prise en charge',
                'verbose_name_plural': 'Types de prise en charge',
                'db_table': 'type_priseencharge',
            },
        ),
        migrations.CreateModel(
            name='TypeQuittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de quittance',
                'verbose_name_plural': 'Types de quittances',
                'db_table': 'type_quittances',
            },
        ),
        migrations.CreateModel(
            name='TypeTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de tarif',
                'verbose_name_plural': 'Types de tarifs',
                'db_table': 'type_tarifs',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_number', models.IntegerField()),
                ('end_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='SpecialiteTypePresta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.specialite')),
                ('type_prestataire', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.typeprestataire')),
            ],
            options={
                'verbose_name': 'Spécialité type prestataire',
                'verbose_name_plural': 'Specialités type prestataire',
                'db_table': 'specialite_type_presta',
            },
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('base_calcul_tm', models.CharField(choices=[('FRAIS REEL', 'Frais Reel'), ('PLAFOND', 'Plafond')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('type_priseencharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typepriseencharge')),
            ],
            options={
                'verbose_name': 'Rubrique',
                'verbose_name_plural': 'Rubriques',
                'db_table': 'rubriques',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.branche')),
            ],
            options={
                'verbose_name': 'Produits',
                'verbose_name_plural': 'Produits',
                'db_table': 'produit',
            },
        ),
        migrations.CreateModel(
            name='PrestataireReseaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_integration', models.DateField(blank=True, null=True)),
                ('date_retrait', models.DateField(blank=True, null=True)),
                ('statut', models.BooleanField(default=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire')),
                ('reseau_soin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.reseausoin')),
            ],
            options={
                'verbose_name': 'Prestataire du réseau de soins',
                'verbose_name_plural': 'Prestataires du réseau de soins',
                'db_table': 'prestataire_reseau_soin',
            },
        ),
        migrations.AddField(
            model_name='prestataire',
            name='secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.secteur'),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='type_prestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.typeprestataire'),
        ),
        migrations.CreateModel(
            name='PrescripteurPrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescripteur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.prescripteur')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire')),
            ],
            options={
                'verbose_name': 'Prescripteur du prestataire',
                'verbose_name_plural': 'Prescripteurs du prestataire',
                'db_table': 'prescripteur_prestataire',
            },
        ),
        migrations.AddField(
            model_name='prescripteur',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.specialite'),
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('indicatif', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.devise')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'db_table': 'pays',
            },
        ),
        migrations.CreateModel(
            name='ParamProduitCompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_com_gestion', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('taux_com_courtage', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.produit')),
            ],
            options={
                'verbose_name': 'Paramètres produits par compagnie',
                'verbose_name_plural': 'Paramètres produits par compagnie',
                'db_table': 'param_produit_compagnie',
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.rubrique')),
            ],
            options={
                'verbose_name': 'Medicament',
                'verbose_name_plural': 'Medicaments',
                'db_table': 'medicaments',
            },
        ),
        migrations.CreateModel(
            name='BureauTaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.FloatField(blank=True, null=True)),
                ('montant', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('taxe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.taxe')),
            ],
            options={
                'verbose_name': 'Taxe appliquée',
                'verbose_name_plural': 'Taxes appliquées',
                'db_table': 'bureau_taxes',
            },
        ),
        migrations.AddField(
            model_name='bureau',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.pays'),
        ),
        migrations.AddField(
            model_name='bureau',
            name='taxes',
            field=models.ManyToManyField(through='configurations.BureauTaxe', to='configurations.Taxe'),
        ),
        migrations.CreateModel(
            name='Affection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('code_cim_10', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.categorieaffection')),
            ],
            options={
                'verbose_name': 'Affection',
                'verbose_name_plural': 'Affections',
                'db_table': 'affections',
            },
        ),
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('delais_carence', models.IntegerField(blank=True, null=True)),
                ('delais_controle', models.IntegerField(blank=True, null=True)),
                ('base_calcul_tm', models.CharField(choices=[('FRAIS REEL', 'Frais Reel'), ('PLAFOND', 'Plafond')], default='FRAIS REEL', max_length=20, null=True)),
                ('option_seance', models.BooleanField(default=False)),
                ('accord_automatique', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.rubrique')),
            ],
            options={
                'verbose_name': 'Acte',
                'verbose_name_plural': 'Actes',
                'db_table': 'actes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('prestataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
