# Generated by Django 3.2.19 on 2023-06-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeprestataire',
            name='code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
