# Generated by Django 3.2.15 on 2024-11-28 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_banque_nom_complet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apporteur',
            name='apporteur_international',
        ),
    ]
