# Generated by Django 3.2.19 on 2023-06-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_jourferie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jourferie',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
