# Generated by Django 3.2.15 on 2024-11-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_remove_apporteur_apporteur_international'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramproduitcompagnie',
            name='taux_com_gestion',
        ),
    ]
