# Generated by Django 3.2.19 on 2023-06-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_periodicite'),
    ]

    operations = [
        migrations.AddField(
            model_name='acte',
            name='option_quantite',
            field=models.BooleanField(default=False),
        ),
    ]
