# Generated by Django 3.2.15 on 2024-12-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_typecompagnie'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branche',
            table='Branche',
        ),
    ]
