# Generated by Django 3.2.15 on 2024-12-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_alter_branche_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionsAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Conditions d'assurance",
                'verbose_name_plural': "Conditions d'assurance",
                'db_table': 'conditions_assurance',
            },
        ),
        migrations.CreateModel(
            name='MoyensTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Moyens de transport',
                'verbose_name_plural': 'Moyens de transport',
                'db_table': 'moyens_transport',
            },
        ),
    ]
