# Generated by Django 3.2.15 on 2025-01-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_conditionsassurance_moyenstransport'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branche',
            table='branche',
        ),
    ]
