# Generated by Django 3.2.19 on 2023-06-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0009_medicament_accord_automatique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire'),
        ),
    ]
