# Generated by Django 3.2.19 on 2023-07-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_alter_user_prestataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='typepersonne',
            name='code',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='cachet',
            field=models.ImageField(blank=True, default='', null=True, upload_to='bureaux/cachets'),
        ),
    ]
