# Generated by Django 3.2.19 on 2023-07-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0011_auto_20230711_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeprestataire',
            name='veos_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
