# Generated by Django 3.2.19 on 2023-07-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0012_typeprestataire_veos_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialite',
            options={'verbose_name': 'specialité', 'verbose_name_plural': 'Specialités'},
        ),
        migrations.AlterModelTable(
            name='specialite',
            table='specialite',
        ),
    ]
