# Generated by Django 3.2.19 on 2023-07-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0013_auto_20230712_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='id_per',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
