# Generated by Django 3.2.19 on 2023-07-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0014_prestataire_id_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='veos_code_soc',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='veos_type_pres',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
