# Generated by Django 3.2.19 on 2023-07-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0015_auto_20230712_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescripteur',
            name='veos_code_specialite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescripteur',
            name='veos_id_per',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
