# Generated by Django 3.2.19 on 2023-07-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0016_auto_20230712_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescripteur',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
