# Generated by Django 3.2.19 on 2023-07-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0017_alter_prescripteur_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_ALIMENT', models.CharField(max_length=100, null=True)),
                ('NOM', models.CharField(max_length=100, null=True)),
                ('PRENOMS', models.CharField(max_length=100, null=True)),
                ('DATE_NAISSANCE', models.CharField(max_length=100, null=True)),
                ('GENRE', models.CharField(max_length=1, null=True)),
                ('CODE_POSTAL', models.CharField(max_length=100, null=True)),
                ('EMAIL', models.CharField(max_length=100, null=True)),
                ('NUMERO_FAMILLE', models.IntegerField(null=True)),
                ('TELEPHONE_FIXE', models.CharField(max_length=100, null=True)),
                ('TELEPHONE_MOBILE', models.CharField(max_length=100, null=True)),
                ('ADRESSE', models.CharField(max_length=100, null=True)),
                ('VILLE', models.CharField(max_length=100, null=True)),
                ('ADHERENT_PRINCIPAL_ID', models.IntegerField(null=True)),
                ('CODE_QUALITE_BENEFICIAIRE', models.CharField(max_length=100, null=True)),
                ('QUALITE_BENEFICIAIRE', models.CharField(max_length=100, null=True)),
                ('DATE_ENTREE', models.CharField(max_length=100, null=True)),
                ('DATE_SORTIE', models.CharField(max_length=100, null=True)),
                ('CD_FORMULE', models.CharField(max_length=100, null=True)),
                ('LIB_FORMULE', models.CharField(max_length=100, null=True)),
                ('CD_COLLEGE', models.CharField(max_length=100, null=True)),
                ('LIB_COLLEGE', models.CharField(max_length=100, null=True)),
                ('ID_NPOL', models.IntegerField(null=True)),
                ('NUMERO_CARTE', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'aliment_sante',
            },
        ),
        migrations.AddField(
            model_name='profession',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
