# Generated by Django 3.2.19 on 2023-07-18 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0018_auto_20230713_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGarant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de garant',
                'verbose_name_plural': 'Types de garant',
                'db_table': 'type_garants',
            },
        ),
        migrations.AddField(
            model_name='compagnie',
            name='type_garant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typegarant'),
        ),
    ]
