# Generated by Django 3.2.19 on 2023-07-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0019_auto_20230718_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='veos_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='veos_code_prestataire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
