# Generated by Django 3.2.19 on 2023-07-21 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0022_sinistreveos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE_REGROUPEMENT_OLEA', models.CharField(max_length=100, null=True)),
                ('LIBELLE_ACTE', models.CharField(max_length=100, null=True)),
                ('CODE_ACTE', models.CharField(max_length=100, null=True)),
                ('LETTRE_CLE', models.CharField(max_length=100, null=True)),
                ('COEF', models.CharField(max_length=100, null=True)),
                ('PRIX_UNITAIRE', models.CharField(max_length=100, null=True)),
                ('COUT_CLASSIQUE', models.CharField(max_length=100, null=True)),
                ('COUT_MUTUELLE', models.CharField(max_length=100, null=True)),
                ('COUT_PUBLIC', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'tarif_excels',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_acte', models.CharField(blank=True, max_length=50, null=True)),
                ('cout_public', models.DecimalField(decimal_places=16, max_digits=50, null=True)),
                ('cout_mutuelle', models.DecimalField(decimal_places=16, max_digits=50, null=True)),
                ('cout_classique', models.DecimalField(decimal_places=16, max_digits=50, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.acte')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'db_table': 'tarifs',
            },
        ),
    ]
