# Generated by Django 3.2.19 on 2023-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0024_auto_20230721_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='cout_classique',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='cout_mutuelle',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='cout_public',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='prix_unitaire',
            field=models.IntegerField(null=True),
        ),
    ]
