# Generated by Django 3.2.19 on 2023-07-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0026_auto_20230721_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='created_by',
        ),
    ]
