# Generated by Django 3.2.19 on 2023-07-22 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0027_remove_tarif_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialiteActeAutorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.acte')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.specialite')),
            ],
            options={
                'verbose_name': 'Acte autorisé',
                'verbose_name_plural': 'Actes autorisés',
                'db_table': 'specialite_acte_autorise',
            },
        ),
    ]
