# Generated by Django 3.2.19 on 2023-07-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0028_specialiteacteautorise'),
    ]

    operations = [
        migrations.AddField(
            model_name='acte',
            name='specialiste_uniquement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialite',
            name='is_specialite',
            field=models.BooleanField(default=True),
        ),
    ]
