# Generated by Django 3.2.15 on 2023-07-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0031_auto_20230725_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type utilisateur',
                'verbose_name_plural': 'Types utilisateurs',
                'db_table': 'type_utilisateurs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='type_utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typeutilisateur'),
        ),
    ]
