# Generated by Django 3.2.15 on 2023-07-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0032_auto_20230728_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistreveos',
            name='NUM_COMPAGNIE',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
