# Generated by Django 3.2.15 on 2023-08-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0034_auto_20230731_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeclient',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
