# Generated by Django 3.2.15 on 2023-08-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0036_cronlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compagnie',
            old_name='addresse',
            new_name='adresse',
        ),
    ]
