# Generated by Django 3.2.15 on 2023-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0037_rename_addresse_compagnie_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorialite',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
