# Generated by Django 3.2.15 on 2023-08-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0038_territorialite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255, null=True)),
                ('DESCRIPTION', models.CharField(max_length=255, null=True)),
                ('PRICE', models.IntegerField(null=True)),
                ('CATEGORY', models.CharField(max_length=100, null=True)),
                ('IMAGE', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
