# Generated by Django 3.2.15 on 2023-08-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0039_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CATEGORY',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='DESCRIPTION',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='IMAGE',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRICE',
            new_name='price',
        ),
    ]
