# Generated by Django 3.2.15 on 2023-08-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0040_auto_20230813_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousRubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('rubrique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.rubrique')),
            ],
            options={
                'verbose_name': 'Sous-rubrique',
                'verbose_name_plural': 'Sous-rubriques',
                'db_table': 'sous_rubriques',
            },
        ),
        migrations.CreateModel(
            name='SousActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('delais_carence', models.IntegerField(blank=True, null=True)),
                ('delais_controle', models.IntegerField(blank=True, null=True)),
                ('base_calcul_tm', models.CharField(choices=[('FRAIS REEL', 'Frais Reel'), ('PLAFOND', 'Plafond')], default='FRAIS REEL', max_length=20, null=True)),
                ('option_seance', models.BooleanField(default=False)),
                ('option_quantite', models.BooleanField(default=False)),
                ('accord_automatique', models.BooleanField(default=False)),
                ('specialiste_uniquement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.acte')),
            ],
            options={
                'verbose_name': 'Sous acte',
                'verbose_name_plural': 'Sous actes',
                'db_table': 'sous_actes',
            },
        ),
        migrations.CreateModel(
            name='ActeSousRubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=True)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.acte')),
                ('sous_rubrique', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.sousrubrique')),
            ],
            options={
                'verbose_name': "Acte d'une sous-rubrique",
                'verbose_name_plural': "Actes d'une sous-rubrique",
                'db_table': 'acte_sous_rubrique',
            },
        ),
    ]
