# Generated by Django 3.2.15 on 2023-08-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0042_auto_20230816_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sousrubriquegroupementacte',
            name='groupement_acte',
        ),
        migrations.RemoveField(
            model_name='sousrubriquegroupementacte',
            name='sous_rubrique',
        ),
        migrations.RemoveField(
            model_name='acte',
            name='groupement',
        ),
        migrations.DeleteModel(
            name='GroupementActe',
        ),
        migrations.DeleteModel(
            name='SousRubriqueGroupementActe',
        ),
    ]
