# Generated by Django 3.2.15 on 2023-08-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0043_auto_20230817_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegroupementActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Regroupement d'acte",
                'verbose_name_plural': "Regroupements d'actes",
                'db_table': 'regroupement_acte',
            },
        ),
        migrations.CreateModel(
            name='SousRubriqueRegroupementActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=True)),
                ('regroupement_acte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.regroupementacte')),
                ('sous_rubrique', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.sousrubrique')),
            ],
            options={
                'verbose_name': 'Contenu de la sous-rubrique',
                'verbose_name_plural': 'Contenus de la sous-rubrique',
                'db_table': 'sous_rubrique_regroupement_acte',
            },
        ),
        migrations.AddField(
            model_name='acte',
            name='regroupement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.regroupementacte'),
        ),
    ]
