# Generated by Django 3.2.15 on 2023-08-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0044_auto_20230817_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='regroupementacte',
            name='rubrique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.rubrique'),
        ),
    ]
