# Generated by Django 3.2.15 on 2023-08-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0045_regroupementacte_rubrique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acte',
            old_name='regroupement',
            new_name='regroupement_acte',
        ),
    ]
