# Generated by Django 3.2.15 on 2023-08-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0046_rename_regroupement_acte_regroupement_acte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='type_prestataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typeprestataire'),
        ),
    ]
