# Generated by Django 3.2.15 on 2023-08-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0047_alter_prestataire_type_prestataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('CUSTOM', 'Custom')], default='DEFAULT', max_length=20, null=True),
        ),
    ]
