# Generated by Django 3.2.15 on 2023-08-31 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0048_user_password_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='coef',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='cout_classique',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='cout_mutuelle',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='cout_public',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='lettre_cle',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='pu_classique',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='pu_mutuelle',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='pu_public',
        ),
        migrations.RemoveField(
            model_name='tarifexcel',
            name='COEF',
        ),
        migrations.RemoveField(
            model_name='tarifexcel',
            name='COUT_CLASSIQUE',
        ),
        migrations.RemoveField(
            model_name='tarifexcel',
            name='COUT_MUTUELLE',
        ),
        migrations.RemoveField(
            model_name='tarifexcel',
            name='COUT_PUBLIC',
        ),
        migrations.RemoveField(
            model_name='tarifexcel',
            name='LETTRE_CLE',
        ),
        migrations.RemoveField(
            model_name='tarifexcel',
            name='PU_CLASSIQUE',
        ),
        migrations.RemoveField(
            model_name='tarifexcel',
            name='PU_MUTUELLE',
        ),
        migrations.RemoveField(
            model_name='tarifexcel',
            name='PU_PUBLIC',
        ),
        migrations.AddField(
            model_name='tarif',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tarif_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarif',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tarif_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
