# Generated by Django 3.2.15 on 2023-08-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0050_auto_20230831_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifexcel',
            name='REGROUPEMENT_ACTE',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
