# Generated by Django 3.2.15 on 2023-09-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0051_tarifexcel_regroupement_acte'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Type d'établissement",
                'verbose_name_plural': "Types d'établissements",
                'db_table': 'type_etablissement',
            },
        ),
        migrations.AddField(
            model_name='prestataire',
            name='type_etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typeetablissement'),
        ),
    ]
