# Generated by Django 3.2.15 on 2023-09-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0052_auto_20230901_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifexcel',
            old_name='LETTRE_PUBLIC_CHU',
            new_name='LETTRE_CLE_PUBLIC_CHU',
        ),
        migrations.RenameField(
            model_name='tarifexcel',
            old_name='LETTRE_PUBLIC_ICA',
            new_name='LETTRE_CLE_PUBLIC_ICA',
        ),
    ]
