# Generated by Django 3.2.15 on 2023-09-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0053_auto_20230901_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='updated_by',
        ),
    ]
