# Generated by Django 3.2.15 on 2023-09-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0054_auto_20230901_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeWaspito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('code_olea', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('code_waspito', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('cotation', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.acte')),
            ],
            options={
                'verbose_name': 'Acte de waspito',
                'verbose_name_plural': 'Actes de waspito',
                'db_table': 'acte_waspito',
            },
        ),
    ]
