# Generated by Django 3.2.15 on 2023-09-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0055_actewaspito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actewaspito',
            name='libelle',
        ),
        migrations.AddField(
            model_name='actewaspito',
            name='libelle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actewaspito',
            name='libelle_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
