# Generated by Django 3.2.15 on 2023-10-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0056_auto_20230912_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SinistreVeos',
        ),
    ]
