# Generated by Django 3.2.15 on 2023-10-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0057_delete_sinistreveos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinistreVeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_SIN', models.CharField(max_length=100, null=True)),
                ('NUMERO', models.CharField(max_length=100, null=True)),
                ('FRAIS_REEL', models.CharField(max_length=100, null=True)),
                ('TICKET_MODERATEUR', models.CharField(max_length=100, null=True)),
                ('DEPASSEMENT', models.CharField(max_length=100, null=True)),
                ('PART_ASSURE', models.CharField(max_length=100, null=True)),
                ('PART_COMPAGNIE', models.CharField(max_length=100, null=True)),
                ('DATE_SURVENANCE', models.CharField(max_length=100, null=True)),
                ('ACTE_ID', models.CharField(max_length=100, null=True)),
                ('AFFECTION_ID', models.CharField(max_length=100, null=True)),
                ('PRESTATAIRE_ID', models.CharField(max_length=100, null=True)),
                ('POLICE_ID', models.CharField(max_length=100, null=True)),
                ('PRESCRIPTEUR_ID', models.CharField(max_length=100, null=True)),
                ('STATUT', models.CharField(max_length=100, null=True)),
                ('ALIMENT_ID', models.CharField(max_length=100, null=True)),
                ('NUM_COMPAGNIE', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'sinistre_veos',
            },
        ),
    ]
