# Generated by Django 3.2.15 on 2023-10-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0058_sinistreveos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='prestaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.prestataire'),
        ),
    ]
