# Generated by Django 3.2.15 on 2023-10-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0059_auto_20231004_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePrefinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de préfinancement',
                'verbose_name_plural': 'Types de préfinancement',
                'db_table': 'type_prefinancement',
            },
        ),
    ]
