# Generated by Django 3.2.15 on 2023-10-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0060_typeprefinancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistreveos',
            name='STATUT_IMPORT',
            field=models.BooleanField(default=True),
        ),
    ]
