# Generated by Django 3.2.15 on 2023-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0062_alter_prestataire_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescripteur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prescripteur',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
