# Generated by Django 3.2.15 on 2023-10-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0065_auto_20231020_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentveos',
            name='DATE_NAISSANCE',
            field=models.DateField(null=True),
        ),
    ]
