# Generated by Django 3.2.15 on 2023-10-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0068_auto_20231025_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeprefinancement',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=15, null=True),
        ),
    ]
