# Generated by Django 3.2.15 on 2023-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0070_modecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modecreation',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
