# Generated by Django 3.2.15 on 2023-10-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0071_alter_modecreation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodecomptable',
            options={'verbose_name': 'Période comptable', 'verbose_name_plural': 'Périodes comptables'},
        ),
        migrations.AlterModelTable(
            name='periodecomptable',
            table='periode_comptable',
        ),
    ]
