# Generated by Django 3.2.15 on 2023-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0073_auto_20231103_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeremboursement',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
