# Generated by Django 3.2.15 on 2023-11-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0076_alter_paramproduitcompagnie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='ville',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
