# Generated by Django 3.2.15 on 2023-11-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0077_prestataire_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='acte',
            name='est_gratuit',
            field=models.BooleanField(default=False),
        ),
    ]
