# Generated by Django 3.2.15 on 2023-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0078_acte_est_gratuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='rb_ordre',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
