# Generated by Django 3.2.15 on 2023-11-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0079_prestataire_rb_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnie',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
