# Generated by Django 3.2.15 on 2023-12-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0080_alter_compagnie_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apporteur',
            old_name='address',
            new_name='addresse',
        ),
        migrations.RenameField(
            model_name='apporteur',
            old_name='last_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='apporteur',
            old_name='first_name',
            new_name='prenoms',
        ),
        migrations.RenameField(
            model_name='apporteur',
            old_name='phone',
            new_name='telephone',
        ),
    ]
