# Generated by Django 5.0 on 2023-12-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0081_auto_20231204_1508"),
    ]

    operations = [
        #migrations.RemoveField(model_name="compagnie", name="taux_com_courtage",),
        #migrations.RemoveField(model_name="compagnie", name="taux_com_gestion",),
    ]
