# Generated by Django 3.2.15 on 2023-12-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0082_auto_20231205_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='affection',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
