# Generated by Django 3.2.15 on 2023-12-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0083_auto_20231206_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataireveos',
            name='NAME',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prestataireveos',
            name='TELEPHONE2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
