# Generated by Django 3.2.15 on 2023-12-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0084_auto_20231206_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescripteurVeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_per', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=200, null=True)),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('specialite', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('ID_PRESTA', models.CharField(blank=True, max_length=50, null=True)),
                ('NUM_PRESTA', models.CharField(blank=True, max_length=100, null=True)),
                ('NOM_PRESTA', models.CharField(blank=True, max_length=100, null=True)),
                ('STATUT_IMPORT', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prescripteur Veos',
                'verbose_name_plural': 'Prescripteurs VEOS',
                'db_table': 'prescripteurs_veos',
            },
        ),
    ]
