# Generated by Django 3.2.15 on 2023-12-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0083_affection_code'),
        ('configurations', '0085_prescripteurveos'),
    ]

    operations = [
    ]
