# Generated by Django 3.2.15 on 2023-12-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0087_auto_20231206_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataireveos',
            name='STATUT_IMPORT',
            field=models.BooleanField(default=False),
        ),
    ]
