# Generated by Django 3.2.15 on 2023-12-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0088_alter_prestataireveos_statut_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_PER', models.CharField(max_length=100, null=True)),
                ('CODE', models.CharField(max_length=100, null=True)),
                ('NOM', models.CharField(max_length=255, null=True)),
                ('PRENOMS', models.CharField(max_length=100, null=True)),
                ('DATE_NAISSANCE', models.CharField(max_length=100, null=True)),
                ('TELEPHONE_FIXE', models.CharField(max_length=100, null=True)),
                ('TELEPHONE_MOBILE', models.CharField(max_length=100, null=True)),
                ('EMAIL', models.CharField(max_length=100, null=True)),
                ('VILLE', models.CharField(max_length=100, null=True)),
                ('ADRESSE', models.CharField(max_length=100, null=True)),
                ('TYPE_PER', models.CharField(max_length=100, null=True)),
                ('LANG', models.CharField(max_length=100, null=True)),
                ('PAYS', models.CharField(max_length=100, null=True)),
                ('BUREAU', models.CharField(max_length=100, null=True)),
                ('STATUT_IMPORT', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client VEOS',
                'verbose_name_plural': 'Clients VEOS',
                'db_table': 'client_veos',
            },
        ),
    ]
