# Generated by Django 3.2.15 on 2023-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0089_clientveos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceVeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMERO', models.CharField(max_length=100, null=True)),
                ('NUMERO_PROVISOIRE', models.CharField(max_length=100, null=True)),
                ('PRIME_TTC', models.CharField(max_length=100, null=True)),
                ('PRIME_NET', models.CharField(max_length=100, null=True)),
                ('DATE_DEBUT_EFFET', models.CharField(max_length=100, null=True)),
                ('DATE_MVT', models.CharField(max_length=100, null=True)),
                ('DATE_FIN_EFFET', models.CharField(max_length=100, null=True)),
                ('ID_NPOL', models.CharField(max_length=100, null=True)),
                ('CLIENT_IDPER', models.CharField(max_length=100, null=True)),
                ('CLIENT_ID', models.CharField(max_length=100, null=True)),
                ('ASS_ID_PER', models.CharField(max_length=100, null=True)),
                ('COMPAGNIE_ID', models.CharField(max_length=100, null=True)),
                ('BUREAU_ID', models.CharField(max_length=100, null=True)),
                ('PRODUIT_ID', models.CharField(max_length=100, null=True)),
                ('DEVISE_ID', models.CharField(max_length=100, null=True)),
                ('PEF_TMOD', models.CharField(max_length=100, null=True)),
                ('PEF_DEPASS', models.CharField(max_length=100, null=True)),
                ('PEF_DOSSIER', models.CharField(max_length=100, null=True)),
                ('STATUT_IMPORT', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Police VEOS',
                'verbose_name_plural': 'Polices VEOS',
                'db_table': 'police_veos',
            },
        ),
    ]
