# Generated by Django 3.2.15 on 2023-12-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0092_policeveos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeveos',
            name='ID_POL',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
