# Generated by Django 3.2.15 on 2023-12-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0093_policeveos_id_pol'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormuleVeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_FORMULE', models.IntegerField()),
                ('CODE_FORMULE', models.CharField(max_length=50)),
                ('LIBELLE_FORMULE', models.CharField(max_length=255)),
                ('NOM_ASSURE', models.CharField(max_length=255)),
                ('NUMERO_ASSURE', models.CharField(max_length=50)),
                ('ID_NPOL', models.IntegerField()),
                ('NUMERO_POLICE', models.CharField(max_length=50)),
                ('DATE_DEBUT', models.DateField()),
                ('DATE_FIN', models.DateField()),
                ('CODE_TYPE_TARIF', models.CharField(max_length=50)),
                ('LIB_TYPE_TARIF', models.CharField(max_length=255)),
                ('CODE_TERRITORIALITE', models.CharField(max_length=50)),
                ('LIB_TERRITORIALITE', models.CharField(max_length=255)),
                ('NUM_SOC', models.CharField(max_length=50)),
                ('STATUT_IMPORT', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formule VEOS',
                'verbose_name_plural': 'Formules VEOS',
                'db_table': 'formule_veos',
            },
        ),
    ]
