# Generated by Django 3.2.15 on 2023-12-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0093_policeveos_id_pol'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurVeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_PER', models.CharField(max_length=100, null=True)),
                ('NOM', models.CharField(max_length=100, null=True)),
                ('PRENOM', models.CharField(max_length=255, null=True)),
                ('CODE', models.CharField(max_length=100, null=True)),
                ('LOGIN', models.CharField(max_length=100, null=True)),
                ('EMAIL', models.CharField(max_length=100, null=True)),
                ('ID_PRESTA', models.CharField(max_length=100, null=True)),
                ('NUM_PRESTA', models.CharField(max_length=100, null=True)),
                ('NOM_PRESTA', models.CharField(max_length=100, null=True)),
                ('SOCIETE', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Utilisateur Veos',
                'verbose_name_plural': 'Utilisateurs VEOS',
                'db_table': 'utilisateurs_veos',
            },
        ),
    ]
