# Generated by Django 3.2.15 on 2023-12-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0094_formuleveos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formuleveos',
            name='CODE_FORMULE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='CODE_TERRITORIALITE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='CODE_TYPE_TARIF',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='DATE_DEBUT',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='DATE_FIN',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='ID_FORMULE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='ID_NPOL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='LIBELLE_FORMULE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='LIB_TERRITORIALITE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='LIB_TYPE_TARIF',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='NOM_ASSURE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='NUMERO_ASSURE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='NUMERO_POLICE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='NUM_SOC',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
