# Generated by Django 3.2.15 on 2023-12-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0094_utilisateurveos'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurveos',
            name='STATUT_IMPORT',
            field=models.BooleanField(default=False),
        ),
    ]
