# Generated by Django 3.2.15 on 2023-12-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0095_auto_20231211_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompagnieVeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_PER', models.CharField(max_length=100, null=True)),
                ('CODE', models.CharField(max_length=100, null=True)),
                ('NOM', models.CharField(max_length=255, null=True)),
                ('TELEPHONE', models.CharField(max_length=100, null=True)),
                ('EMAIL', models.CharField(max_length=100, null=True)),
                ('ADRESSE', models.CharField(max_length=100, null=True)),
                ('BUREAU', models.CharField(max_length=100, null=True)),
                ('STATUT_IMPORT', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compagnie VEOS',
                'verbose_name_plural': 'Compagnies VEOS',
                'db_table': 'compagnie_veos',
            },
        ),
    ]
