# Generated by Django 3.2.15 on 2023-12-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0095_utilisateurveos_statut_import'),
        ('configurations', '0096_compagnieveos'),
    ]

    operations = [
    ]
