# Generated by Django 3.2.15 on 2023-12-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0098_alter_prescripteurveos_statut_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentveos',
            name='ADRESSE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientveos',
            name='ADRESSE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientveos',
            name='STATUT_IMPORT',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compagnieveos',
            name='ADRESSE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compagnieveos',
            name='STATUT_IMPORT',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formuleveos',
            name='STATUT_IMPORT',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policeveos',
            name='STATUT_IMPORT',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prestataireveos',
            name='ADRESSE',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
