# Generated by Django 3.2.15 on 2023-12-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0099_auto_20231212_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuittanceVeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMERO_CLIENT', models.CharField(max_length=255)),
                ('NOM_CLIENT', models.CharField(max_length=255)),
                ('NUMERO_COMPAGNIE', models.CharField(max_length=255)),
                ('NOM_COMPAGNIE', models.CharField(max_length=255)),
                ('NUMERO_APPORTEUR', models.CharField(max_length=255)),
                ('NOM_APPORTEUR', models.CharField(max_length=255)),
                ('CODE_PRODUIT', models.CharField(max_length=255)),
                ('LIBELLE_PRODUIT', models.CharField(max_length=255)),
                ('NUMERO_POLICE', models.CharField(max_length=255)),
                ('NUMERO_QUITTANCE', models.CharField(max_length=255)),
                ('DATE_EMIS', models.DateField()),
                ('DATE_DEBUT', models.DateField()),
                ('DATE_FIN', models.DateField()),
                ('CODE_TYPE_QUITTANCE', models.CharField(max_length=255)),
                ('LIBELLE_TYPE_QUITTANCE', models.CharField(max_length=255)),
                ('CODE_NATURE_QUITTANCE', models.CharField(max_length=255)),
                ('LIBELLE_NATURE_QUITTANCE', models.CharField(max_length=255)),
                ('CODE_SITUATION_CLIENT', models.CharField(max_length=255)),
                ('LIBELLE_SITUATION_CLIENT', models.CharField(max_length=255)),
                ('DATE_SITUATION_CLIENT', models.DateField()),
                ('CODE_SITUATION_COMPAGNIE', models.CharField(max_length=255)),
                ('LIBELLE_SITUATION_COMPAGNIE', models.CharField(max_length=255)),
                ('DATE_SITUATION_COMPAGNIE', models.DateField()),
                ('CODE_SITUATION_APPORTEUR', models.CharField(max_length=255)),
                ('LIBELLE_SITUATION_APPORTEUR', models.CharField(max_length=255)),
                ('DATE_SITUATION_APPORTEUR', models.DateField()),
                ('MOIS_DE_COMPTE', models.CharField(max_length=255)),
                ('PRIME_NETTE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CSS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CSS_OLEA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CARTE_ROSE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CONSTAT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ACCESSOIRES', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ACCESSOIRES_CIE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TAXES', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TSVL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRIME_TOTALE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRIME_TTC_HORS_CSS_HORS_CARTE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRIME_TTC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TAUX', models.DecimalField(decimal_places=2, max_digits=5)),
                ('COMMISSION', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SOLDE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('INDICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NUMERO_SOCIETE', models.CharField(max_length=255)),
                ('CODE_MOUVEMENT', models.CharField(max_length=255)),
                ('LIBELLE_MOUVEMENT', models.CharField(max_length=255)),
                ('CODE_MOTIF', models.CharField(max_length=255)),
                ('LIBELLE_MOTIF', models.CharField(max_length=255)),
                ('STATUT_IMPORT', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quittance Veos',
                'verbose_name_plural': 'Quittances VEOS',
                'db_table': 'quittances_veos',
            },
        ),
    ]
