# Generated by Django 3.2.15 on 2023-12-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0100_quittanceveos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittanceveos',
            name='CODE_MOTIF',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='CODE_MOUVEMENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='CODE_NATURE_QUITTANCE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='CODE_PRODUIT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='CODE_SITUATION_APPORTEUR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='CODE_SITUATION_CLIENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='CODE_SITUATION_COMPAGNIE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='CODE_TYPE_QUITTANCE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='LIBELLE_MOTIF',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='LIBELLE_MOUVEMENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='LIBELLE_NATURE_QUITTANCE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='LIBELLE_PRODUIT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='LIBELLE_SITUATION_APPORTEUR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='LIBELLE_SITUATION_CLIENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='LIBELLE_SITUATION_COMPAGNIE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='LIBELLE_TYPE_QUITTANCE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='MOIS_DE_COMPTE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='NOM_APPORTEUR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='NOM_CLIENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='NOM_COMPAGNIE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='NUMERO_APPORTEUR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='NUMERO_CLIENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='NUMERO_COMPAGNIE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='NUMERO_POLICE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='NUMERO_QUITTANCE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='NUMERO_SOCIETE',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
