# Generated by Django 3.2.15 on 2023-12-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0103_auto_20231214_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittanceveos',
            name='DATE_DEBUT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='DATE_EMIS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='DATE_FIN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='DATE_SITUATION_APPORTEUR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='DATE_SITUATION_CLIENT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quittanceveos',
            name='DATE_SITUATION_COMPAGNIE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
