# Generated by Django 3.2.15 on 2023-12-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0106_auto_20231215_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramacte',
            name='option_quantite',
        ),
        migrations.RemoveField(
            model_name='paramacte',
            name='option_seance',
        ),
    ]
