# Generated by Django 3.2.15 on 2023-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0107_auto_20231215_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramacte',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
