# Generated by Django 3.2.15 on 2023-12-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0109_alter_paramacte_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramacte',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paramacte',
            name='updated_at',
        ),
    ]
