# Generated by Django 3.2.15 on 2023-12-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0110_auto_20231215_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramacte',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paramacte',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
