# Generated by Django 3.2.15 on 2023-12-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0111_auto_20231215_1902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paramacte',
            unique_together={('bureau', 'acte')},
        ),
    ]
