# Generated by Django 3.2.15 on 2023-12-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0112_alter_paramacte_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paramacte',
            unique_together=set(),
        ),
    ]
