# Generated by Django 3.2.15 on 2023-12-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0082_remove_compagnie_taux_com_courtage_and_more'),
        ('configurations', '0113_alter_paramacte_unique_together'),
    ]

    operations = [
    ]
