# Generated by Django 3.2.15 on 2023-12-21 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0115_auto_20231221_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='prestaire',
            new_name='prestataire',
        ),
    ]
