# Generated by Django 3.2.15 on 2023-12-22 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0116_rename_prestaire_tarif_prestataire'),
    ]

    operations = [
       migrations.AddField(
           model_name='tarif',
           name='created_by',
           field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
       ),
        migrations.AddField(
            model_name='tarif',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime')], default='VALIDE', max_length=15, null=True),
        ),
    ]
