# Generated by Django 3.2.15 on 2023-12-22 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0117_auto_20231222_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='validated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
