# Generated by Django 3.2.15 on 2023-12-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0119_auto_20231222_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramproduitcompagnie',
            name='taux_com_courtage_terme',
            field=models.FloatField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paramproduitcompagnie',
            name='taux_com_courtage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paramproduitcompagnie',
            name='taux_com_gestion',
            field=models.FloatField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
