# Generated by Django 3.2.15 on 2023-12-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0120_auto_20231225_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='acte',
            name='lettre_cle',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
