# Generated by Django 3.2.15 on 2023-12-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0120_auto_20231225_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='quittanceveos',
            name='ID_NPOL',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
