# Generated by Django 3.2.15 on 2023-12-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0122_alter_acte_lettre_cle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True),
        ),
    ]
