# Generated by Django 3.2.15 on 2023-12-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0123_alter_tarif_statut_validite'),
    ]

    operations = [
        migrations.AddField(
            model_name='branche',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
