# Generated by Django 3.2.15 on 2023-12-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0121_quittanceveos_id_npol'),
        ('configurations', '0125_apporteur_status'),
    ]

    operations = [
    ]
