# Generated by Django 3.2.15 on 2023-12-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0126_merge_20231228_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='apporteur',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau'),
        ),
    ]
