# Generated by Django 3.2.15 on 2024-01-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0127_apporteur_bureau'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeveos',
            name='MONTANTCOM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policeveos',
            name='MONTANTGEST',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policeveos',
            name='PREAV_RESIL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policeveos',
            name='TAUXCOM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policeveos',
            name='TAUXGEST',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
