# Generated by Django 3.2.15 on 2024-01-15 09:40
# Generated by Django 3.2.15 on 2024-01-10 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0056_mouvementaliment'),
        ('configurations', '0128_auto_20240109_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='utilisateur_grh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.client'),
        ),
    ]
