# Generated by Django 3.2.15 on 2024-01-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0129_user_utilisateur_grh'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseausoin',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau'),
        ),
    ]
