# Generated by Django 3.2.15 on 2024-01-15 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0130_reseausoin_bureau'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatairereseaux',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
