# Generated by Django 3.2.15 on 2024-01-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0131_prestatairereseaux_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseausoin',
            name='code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
