# Generated by Django 3.2.15 on 2024-01-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0132_reseausoin_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrestataireReseaux',
            new_name='PrestataireReseauSoin',
        ),
        migrations.AddField(
            model_name='reseausoin',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
