# Generated by Django 3.2.15 on 2024-01-18 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0133_auto_20240116_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestatairereseausoin',
            name='statut',
        ),
        migrations.AddField(
            model_name='prestatairereseausoin',
            name='removed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='removed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestatairereseausoin',
            name='statut_validite',
            field=models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True),
        ),
    ]
