# Generated by Django 3.2.15 on 2024-01-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0129_rename_value_keyvaluedata_data'),
        ('configurations', '0134_auto_20240118_1326'),
    ]

    operations = [
    ]
