# Generated by Django 3.2.15 on 2024-01-22 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0135_merge_20240119_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestatairereseausoin',
            name='date_integration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestatairereseausoin',
            name='date_retrait',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestatairereseausoin',
            name='prestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ses_reseaux_soins', to='configurations.prestataire'),
        ),
        migrations.AlterField(
            model_name='prestatairereseausoin',
            name='reseau_soin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ses_prestataires', to='configurations.reseausoin'),
        ),
    ]
