# Generated by Django 3.2.15 on 2024-01-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0135_merge_20240119_1144'),
        ('configurations', '0136_auto_20240122_0201'),
    ]

    operations = [
    ]
