# Generated by Django 3.2.15 on 2024-01-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0137_merge_20240123_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='formuleveos',
            name='LIGNE1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formuleveos',
            name='LIGNE2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formuleveos',
            name='LIGNE3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formuleveos',
            name='LIGNE4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formuleveos',
            name='LIGNE5',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
