# Generated by Django 4.0.3 on 2024-01-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0138_auto_20240125_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=40, null=True),
        ),
    ]
