# Generated by Django 4.0.3 on 2024-01-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0139_prestataire_latitude_prestataire_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=40, null=True),
        ),
    ]
