# Generated by Django 3.2.15 on 2024-01-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0140_alter_prestataire_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturequittance',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='typequittance',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
