# Generated by Django 3.2.15 on 2024-02-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0141_auto_20240130_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='option_export_beneficiaires',
            field=models.BooleanField(default=True),
        ),
    ]
