# Generated by Django 3.2.15 on 2024-02-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0143_auto_20240205_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApporteurVeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LIB_TIT', models.CharField(max_length=100, null=True)),
                ('NUM_PER', models.CharField(max_length=100, null=True)),
                ('NOM_PER', models.CharField(max_length=100, null=True)),
                ('PRENOM_PER', models.CharField(max_length=100, null=True)),
                ('ADRESSE1_ADR', models.CharField(max_length=255, null=True)),
                ('ADRESSE2_ADR', models.CharField(max_length=255, null=True)),
                ('ADRESSE3_ADR', models.CharField(max_length=255, null=True)),
                ('CD_PST', models.CharField(max_length=100, null=True)),
                ('VILLE_ADR', models.CharField(max_length=100, null=True)),
                ('LIB_PAYS', models.CharField(max_length=100, null=True)),
                ('FIXE', models.CharField(max_length=100, null=True)),
                ('MOBILE', models.CharField(max_length=100, null=True)),
                ('EMAIL', models.CharField(max_length=100, null=True)),
                ('ID_NPOL', models.CharField(max_length=100, null=True)),
                ('CONTRAT', models.CharField(max_length=100, null=True)),
                ('EFFET', models.DateField(null=True)),
                ('CIE', models.CharField(max_length=100, null=True)),
                ('ID_PER_APPORTEUR', models.CharField(max_length=100, null=True)),
                ('NUM_APPORTEUR', models.CharField(max_length=100, null=True)),
                ('NOM_APPORTEUR', models.CharField(max_length=100, null=True)),
                ('PRENOM_APPORTEUR', models.CharField(max_length=100, null=True)),
                ('TXT_CINT', models.CharField(max_length=100, null=True)),
                ('TXC_CINT', models.CharField(max_length=100, null=True)),
                ('STATUT_IMPORT', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Apporteur veos',
                'verbose_name_plural': 'Apporteurs veos',
                'db_table': 'apporteur_veos',
            },
        ),
    ]
