# Generated by Django 3.2.15 on 2024-02-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0144_apporteurveos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apporteur',
            old_name='addresse',
            new_name='adresse',
        ),
    ]
