# Generated by Django 3.2.15 on 2024-02-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0145_rename_addresse_apporteur_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apporteur',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apporteur',
            name='fax',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='apporteur',
            name='nom',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apporteur',
            name='prenoms',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apporteur',
            name='telephone',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
