# Generated by Django 3.2.15 on 2024-02-06 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0147_apporteur_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apporteur',
            name='fax',
        ),
        migrations.AddField(
            model_name='apporteur',
            name='is_inter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apporteur',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.pays'),
        ),
        migrations.AlterField(
            model_name='typeremboursement',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
