# Generated by Django 3.2.15 on 2024-02-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0152_auto_20240210_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='natureoperation',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
