# Generated by Django 3.2.15 on 2024-02-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0081_policeclient'),
        ('configurations', '0154_auto_20240227_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utilisateur_grh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.client', verbose_name='Client (GRH)'),
        ),
    ]
