# Generated by Django 3.2.15 on 2024-02-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0154_auto_20240227_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='code_courtier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
