# Generated by Django 3.2.15 on 2024-03-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0155_alter_user_utilisateur_grh'),
        ('configurations', '0155_bureau_code_courtier'),
    ]

    operations = [
    ]
