# Generated by Django 3.2.15 on 2024-03-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0156_merge_20240301_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='WsBoby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WS Boby',
                'verbose_name_plural': 'WS Boby',
                'db_table': 'ws_boby',
            },
        ),
        migrations.CreateModel(
            name='ParamWsBoby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ws_boby', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.wsboby')),
            ],
            options={
                'verbose_name': 'Param WS Boby',
                'verbose_name_plural': 'Param WS Boby',
                'db_table': 'param_ws_boby',
            },
        ),
    ]
