# Generated by Django 3.2.15 on 2024-03-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0157_paramwsboby_wsboby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsboby',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
