# Generated by Django 3.2.15 on 2024-04-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0159_typeprestataire_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='ca_type',
            field=models.CharField(blank=True, choices=[('EMISSION', 'EMISSION'), ('REVERSEMENT', 'REVERSEMENT')], default='REVERSEMENT', max_length=50, null=True, verbose_name='CA'),
        ),
    ]
