# Generated by Django 3.2.15 on 2024-04-22 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0160_bureau_ca_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundQueryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='background_query')),
                ('status', models.CharField(choices=[('ENATT', 'EN ATTENTE'), ('ENCOURS', 'EN COURS'), ('ECHOUEE', 'ECHOUEE'), ('ANNULLEE', 'ANNULLEE'), ('TERMINEE', 'TERMINEE')], default='ENATT', max_length=15, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Background Query Task',
                'verbose_name_plural': 'Background Query Tasks',
                'db_table': 'background_query_task',
            },
        ),
    ]
