# Generated by Django 3.2.15 on 2024-04-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0160_bureau_ca_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
