# Generated by Django 3.2.15 on 2024-04-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0161_backgroundquerytask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundquerytask',
            options={'verbose_name': 'Requête en arrière-plan', 'verbose_name_plural': 'Requête en arrière-plan'},
        ),
        migrations.AlterField(
            model_name='backgroundquerytask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='backgroundquerytask',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name="Message d'erreur"),
        ),
        migrations.AlterField(
            model_name='backgroundquerytask',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='background_query', verbose_name='Fichier excel'),
        ),
        migrations.AlterField(
            model_name='backgroundquerytask',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Libellé requête'),
        ),
        migrations.AlterField(
            model_name='backgroundquerytask',
            name='query',
            field=models.TextField(blank=True, null=True, verbose_name='Requête'),
        ),
        migrations.AlterField(
            model_name='backgroundquerytask',
            name='status',
            field=models.CharField(choices=[('ENATT', 'EN ATTENTE'), ('ENCOURS', 'EN COURS'), ('ECHOUEE', 'ECHOUEE'), ('ANNULLEE', 'ANNULLEE'), ('TERMINEE', 'TERMINEE')], default='ENATT', max_length=15, null=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='backgroundquerytask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
