# Generated by Django 3.2.15 on 2024-04-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0161_bureau_status'),
        ('configurations', '0162_auto_20240424_1218'),
    ]

    operations = [
    ]
