# Generated by Django 3.2.15 on 2024-04-26 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0163_merge_0161_bureau_status_0162_auto_20240424_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_group',
            field=models.BooleanField(default=False, verbose_name='Statut admin groupe'),
        ),
        migrations.CreateModel(
            name='AdminGroupeBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Groupe Permission',
                'verbose_name_plural': 'Groupes Permissions',
                'db_table': 'admin_groupe_permission',
            },
        ),
    ]
