# Generated by Django 3.2.15 on 2024-04-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0164_auto_20240426_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admingroupebureau',
            options={'verbose_name': 'Admin Groupe Bureau', 'verbose_name_plural': 'Admin Groupes Bureaux'},
        ),
    ]
