# Generated by Django 3.2.15 on 2024-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0165_alter_admingroupebureau_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='ville',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
