# Generated by Django 3.2.15 on 2024-05-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0168_rename_commentaire_bureau_mention_legale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='mention_legale',
            field=models.TextField(blank=True, null=True),
        ),
    ]
