# Generated by Django 3.2.15 on 2024-05-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0169_alter_bureau_mention_legale'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurGrhVeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM', models.CharField(max_length=100, null=True)),
                ('LOGIN', models.CharField(max_length=100, null=True)),
                ('ADMIN', models.CharField(max_length=100, null=True)),
                ('SUPERVUE', models.CharField(max_length=100, null=True)),
                ('ACCES_SANTE', models.CharField(max_length=100, null=True)),
                ('NOM_CLIENT', models.CharField(max_length=100, null=True)),
                ('CODE_CLIENT', models.CharField(max_length=100, null=True)),
                ('STATUT_IMPORT', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Utilisateur GRH Veos',
                'verbose_name_plural': 'Utilisateurs GRH VEOS',
                'db_table': 'utilisateurs_grh_veos',
            },
        ),
    ]
