# Generated by Django 3.2.15 on 2024-05-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0172_changementformule_sousregroupementacte_sousregroupementacteacte'),
    ]

    operations = [
        migrations.AddField(
            model_name='changementformule',
            name='MOTIF',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
