# Generated by Django 3.2.15 on 2024-05-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0173_auto_20240525_1121'),
        ('configurations', '0173_changementformule_motif'),
    ]

    operations = [
    ]
