# Generated by Django 3.2.15 on 2024-05-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0175_remove_compagnie_has_taux_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='option_assurance_universelle',
            field=models.BooleanField(default=False),
        ),
    ]
