# Generated by Django 3.2.15 on 2024-05-29 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0175_remove_compagnie_has_taux_multiple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.compagnie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caution',
                'verbose_name_plural': 'Cautions',
                'db_table': 'caution',
            },
        ),
    ]
