# Generated by Django 3.2.15 on 2024-06-04 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0176_caution'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescripteurprestataire',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pp_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescripteurprestataire',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pp_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
