# Generated by Django 3.2.15 on 2024-05-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0176_bureau_option_assurance_universelle'),
        ('configurations', '0176_caution'),
    ]

    operations = [
    ]
