# Generated by Django 3.2.15 on 2024-06-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0177_auto_20240604_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentMatricule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_ADH', models.CharField(max_length=100, null=True)),
                ('NOM', models.CharField(max_length=100, null=True)),
                ('PRENOMS', models.CharField(max_length=100, null=True)),
                ('NUMERO_CARTE', models.CharField(max_length=100, null=True)),
                ('MATRICULE', models.CharField(max_length=100, null=True)),
                ('STATUT_IMPORT', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'aliment_matricule',
            },
        ),
    ]
