# Generated by Django 3.2.15 on 2024-06-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0178_alimentmatricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramacte',
            name='delais_carence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
