# Generated by Django 3.2.15 on 2024-06-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0180_alter_bureau_tarfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='fuseau_horaire',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
