# Generated by Django 3.2.15 on 2024-06-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0177_merge_20240531_1446'),
        ('configurations', '0182_alimentbaobab'),
    ]

    operations = [
    ]
