# Generated by Django 3.2.15 on 2024-06-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0184_bureau_type_bon_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeinter',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
