# Generated by Django 3.2.15 on 2024-06-25 12:36

import configurations.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0185_groupeinter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramproduitcompagnie',
            name='taux_com_courtage',
            field=configurations.models.FloatRangeField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paramproduitcompagnie',
            name='taux_com_courtage_terme',
            field=configurations.models.FloatRangeField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paramproduitcompagnie',
            name='taux_com_gestion',
            field=configurations.models.FloatRangeField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
