# Generated by Django 3.2.15 on 2024-06-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0186_auto_20240625_1236'),
        ('configurations', '0186_remove_acte_delais_carence'),
    ]

    operations = [
    ]
