# Generated by Django 3.2.15 on 2024-06-28 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0187_merge_20240626_0926'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='acte',
        #    name='delais_carence',
        #),
        migrations.CreateModel(
            name='ApporteurInternational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=25, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.pays')),
            ],
            options={
                'verbose_name': 'Apporteur international',
                'verbose_name_plural': 'Apporteurs internationaux',
                'db_table': 'apporteur_international',
            },
        ),
        migrations.AddField(
            model_name='apporteur',
            name='apporteur_international',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.apporteurinternational'),
        ),
    ]
