# Generated by Django 4.2.13 on 2024-06-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0188_auto_20240628_1201'),
    ]

    operations = [
    ]
