# Generated by Django 3.2.15 on 2024-06-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0189_auto_20240628_1502'),
    ]

    operations = [
    ]
