# Generated by Django 3.2.15 on 2024-06-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0190_remove_acte_delais_carence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupeinter',
            old_name='name',
            new_name='nom',
        ),
        #migrations.RemoveField(
        #    model_name='acte',
        #    name='delais_carence',
        #),
        migrations.AddField(
            model_name='groupeinter',
            name='apporteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.apporteur'),
        ),
    ]
