# Generated by Django 3.2.15 on 2024-06-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0191_auto_20240628_1641'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='acte',
        #    name='delais_carence',
        #),
    ]

