# Generated by Django 3.2.15 on 2024-06-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0187_merge_20240625_1326'),
        ('configurations', '0191_auto_20240628_1641'),
    ]

    operations = [
    ]
