# Generated by Django 3.2.15 on 2024-06-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0192_remove_acte_delais_carence'),
    ]

    operations = [
        migrations.AddField(
            model_name='apporteurveos',
            name='APPORTEUR_INTER',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
