# Generated by Django 3.2.15 on 2024-06-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0192_merge_20240628_1709'),
        ('configurations', '0192_remove_acte_delais_carence'),
    ]

    operations = [
    ]
