# Generated by Django 3.2.15 on 2024-07-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0189_remove_acte_delais_carence'),
        ('configurations', '0194_auto_20240628_2130'),
    ]

    operations = [
    ]
