# Generated by Django 3.2.15 on 2024-07-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0195_merge_20240702_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramacte',
            name='entente_prealable',
            field=models.BooleanField(default=False),
        ),
    ]
