# Generated by Django 3.2.15 on 2024-07-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0193_merge_20240628_1740'),
        ('configurations', '0198_auto_20240703_1638'),
    ]

    operations = [
    ]
