# Generated by Django 3.2.15 on 2024-07-05 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0198_auto_20240703_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLettreCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True, verbose_name='Modèle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.banque')),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='model_lettre_cheque_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle lettre cheque',
                'verbose_name_plural': 'Modèles lettre cheque',
                'db_table': 'model_lettre_cheque',
            },
        ),
    ]
