# Generated by Django 3.2.15 on 2024-07-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0110_merge_20240716_1524'),
        ('configurations', '0199_merge_20240716_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_grh',
            field=models.ManyToManyField(blank=True, related_name='client_grh', to='production.Client', verbose_name='Client (GRH)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utilisateur_grh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.client', verbose_name='Client par default'),
        ),
    ]
