# Generated by Django 3.2.15 on 2024-07-12 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0199_modellettrecheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauLettreCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, null=True)),
                ('nombre', models.IntegerField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='bordereau_lettre_cheque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date d’édition')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.bureau')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bordereau_lettre_cheque_created_by', to=settings.AUTH_USER_MODEL)),
                ('model_lettre_cheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.modellettrecheque')),
            ],
            options={
                'verbose_name': 'Historique des lettres Chèques',
                'verbose_name_plural': 'Historique des lettres Chèques',
                'db_table': 'bordereau_lettre_cheque',
            },
        ),
    ]
