# Generated by Django 3.2.15 on 2024-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0199_retenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='retenue',
            name='type_prestataire',
            field=models.ManyToManyField(blank=True, related_name='type_prestataire', to='configurations.TypePrestataire', verbose_name='Types Prestataires'),
        ),
    ]
