# Generated by Django 3.2.15 on 2024-07-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0200_bordereaulettrecheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereaulettrecheque',
            name='libelle',
            field=models.CharField(max_length=100, null=True, verbose_name='libellé'),
        ),
    ]
