# Generated by Django 3.2.15 on 2024-07-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0200_auto_20240716_1524'),
        ('configurations', '0201_alter_bordereaulettrecheque_libelle'),
    ]

    operations = [
    ]
