# Generated by Django 3.2.15 on 2024-07-26 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0113_merge_20240726_1108'),
        ('configurations', '0202_merge_20240726_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='poligamie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='utilisateur_grh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.client', verbose_name='Client (GRH)'),
        ),
    ]
