# Generated by Django 3.2.15 on 2024-08-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0203_auto_20240726_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateurgrhveos',
            options={'verbose_name': 'Utilisateur GRH VEOS', 'verbose_name_plural': 'Utilisateurs GRH VEOS'},
        ),
        migrations.AlterField(
            model_name='utilisateurgrhveos',
            name='ACCES_SANTE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurgrhveos',
            name='ADMIN',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurgrhveos',
            name='BUREAU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurgrhveos',
            name='CODE_CLIENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurgrhveos',
            name='LOGIN',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurgrhveos',
            name='NOM',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurgrhveos',
            name='NOM_CLIENT',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurgrhveos',
            name='SUPERVUE',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
