# Generated by Django 3.2.15 on 2024-08-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0200_retenue_type_prestataire'),
        ('configurations', '0204_auto_20240808_1755'),
    ]

    operations = [
    ]
