# Generated by Django 3.2.15 on 2024-08-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0206_auto_20240822_1720'),
        #('configurations', '0207_merge_20240816_1724'),
    ]

    operations = [
    ]
