# Generated by Django 4.2.14 on 2024-08-23 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0209_alter_mailinglist_nombre_alerte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ml_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
