# Generated by Django 4.2.14 on 2024-08-23 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0211_alter_mailinglist_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'verbose_name': 'Liste de diffusion', 'verbose_name_plural': 'Liste de diffusion'},
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ml_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ml_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
