# Generated by Django 3.2.15 on 2024-09-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0212_alter_mailinglist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinistreveos',
            name='ACTE_ID',
        ),
        migrations.RemoveField(
            model_name='sinistreveos',
            name='AFFECTION_ID',
        ),
        migrations.RemoveField(
            model_name='sinistreveos',
            name='ALIMENT_ID',
        ),
        migrations.RemoveField(
            model_name='sinistreveos',
            name='DATE_SURVENANCE',
        ),
        migrations.RemoveField(
            model_name='sinistreveos',
            name='DEPASSEMENT',
        ),
        migrations.RemoveField(
            model_name='sinistreveos',
            name='NUMERO',
        ),
        migrations.RemoveField(
            model_name='sinistreveos',
            name='NUM_COMPAGNIE',
        ),
        migrations.RemoveField(
            model_name='sinistreveos',
            name='POLICE_ID',
        ),
        migrations.RemoveField(
            model_name='sinistreveos',
            name='PRESCRIPTEUR_ID',
        ),
        migrations.RemoveField(
            model_name='sinistreveos',
            name='PRESTATAIRE_ID',
        ),
        migrations.RemoveField(
            model_name='sinistreveos',
            name='STATUT',
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='ADHERENT_PRINCIPAL',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='AFFECTION',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='CATEG_PRESTA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='CD_FORMULE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='CENTRE_PRESCRIPTEUR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='CLIENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='CODE_ACTE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='CODE_AFFECTION',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='CODE_COMPAGNIE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='CODE_SOCIETE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='COMPAGNIE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='DATE_DE_RECEPTION_FACTURE',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='DATE_ORD',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='DATE_ORD_EN',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='DATE_REG',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='DATE_REG_EN',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='DATE_SINISTRE',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='DATE_SINISTRE_EN',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='DATNAISS_ADH',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='DATNAISS_ADH_EN',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='DEPASSEMENT_EXCLUSION',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='FAR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='ID_ADHERENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='ID_MED_PRESC',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='ID_MED_TRAITANT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='ID_NPOL',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='ID_PER_PRESTA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='MATRICULE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='MEDECIN_PRESCRIPTEUR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='MEDECIN_TRAITANT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='NET_REGLE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='NOM_BENEFICIAIRE_DU_REMB',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='NOM_PATIENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='NOM_PRESTA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='NUMERO_BORDEREAU',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='NUMERO_CARTE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='NUMERO_DOSSIER',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='NUMERO_LCHQ',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='NUMERO_POLICE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='NUM_BENEFICIAIRE_DU_REMB',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='NUM_FACTURE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='PART_OLEA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='PRENOM_PATIENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='REGROUPEMENT_OLEA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='RESEAU_SOIN',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='SPECIALITE_MEDECIN_PRESCRIPTEUR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='SPECIALITE_MEDECIN_TRAITANT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='STATUT_PATIENT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='TICKET_PREFINANCE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='TPS',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinistreveos',
            name='TYPE_ASSURE',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
