# Generated by Django 3.2.15 on 2024-09-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0208_merge_20240828_1839'),
        ('configurations', '0213_auto_20240903_1738'),
    ]

    operations = [
    ]
