# Generated by Django 3.2.15 on 2024-09-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0213_auto_20240903_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistreveos',
            name='OBSERVATION',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
