# Generated by Django 3.2.15 on 2024-09-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0214_merge_20240903_2157'),
        ('configurations', '0214_sinistreveos_observation'),
    ]

    operations = [
    ]
