# Generated by Django 3.2.15 on 2024-09-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0215_acte_statut_validite'),
        ('configurations', '0215_merge_20240904_1549'),
    ]

    operations = [
    ]
