# Generated by Django 3.2.15 on 2024-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0216_merge_20240909_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistreveos',
            name='SESSION_UUID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
