# Generated by Django 3.2.15 on 2024-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0218_periodeveos'),
    ]

    operations = [
        migrations.AddField(
            model_name='typequittance',
            name='code_veos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
