# Generated by Django 3.2.15 on 2024-09-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0220_naturequittance_code_veos'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatExcelWsBoby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_fr', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('libelle_en', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('libelle_pt', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('code_ws', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stat Excel Ws Boby',
                'verbose_name_plural': 'Stats Excel Ws Boby',
                'db_table': 'stat_excel_ws_boby',
            },
        ),
    ]
