# Generated by Django 3.2.15 on 2024-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0221_statexcelwsboby'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptePrestataireVeos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE_PRESTATAIRE', models.CharField(max_length=255, null=True)),
                ('NOM_PRESTATAIRE', models.CharField(max_length=255, null=True)),
                ('EMAIL', models.CharField(max_length=255, null=True)),
                ('REMBOURSEMENT_ORDRE_DE', models.CharField(max_length=255, null=True)),
                ('TYPE_PRESTATAIRE', models.CharField(max_length=255, null=True)),
                ('SECTEUR_PRESTATAIRE', models.CharField(max_length=255, null=True)),
                ('OBSERVATION', models.TextField(null=True)),
                ('STATUT_IMPORT', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Compte Prestataire VEOS',
                'verbose_name_plural': 'Comptes Prestataires VEOS',
                'db_table': 'compte_prestataire_veos',
            },
        ),
    ]
