# Generated by Django 3.2.15 on 2024-10-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0187_merge_20240625_1629'),
        ('configurations', '0222_compteprestataireveos'),
    ]

    operations = [
    ]
