# Generated by Django 3.2.15 on 2024-10-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0223_merge_20241010_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='code_courtier',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
