# Generated by Django 3.2.15 on 2024-10-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0227_alter_compagnie_code_courtier'),
    ]

    operations = [
        migrations.AddField(
            model_name='authgroup',
            name='libelle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authgroup',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
