# Generated by Django 3.2.15 on 2024-11-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0228_auto_20241031_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Unit',
                'verbose_name_plural': 'Business Unit',
                'db_table': 'business_unit',
            },
        ),
    ]
