# Generated by Django 3.2.15 on 2024-11-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0229_businessunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type Produit',
                'verbose_name_plural': 'Type Produit',
                'db_table': 'type_produit',
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='typeproduit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='configurations.typeproduit'),
        ),
    ]
