# Generated by Django 3.2.15 on 2024-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0229_auto_20241125_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantie',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
