# Generated by Django 3.2.15 on 2024-11-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0230_auto_20241122_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='typeproduit',
            new_name='type_produit',
        ),
    ]
