# Generated by Django 3.2.15 on 2024-11-26 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0230_garantie_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantieFormule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.formule')),
                ('garantie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configurations.garantie')),
            ],
            options={
                'verbose_name': 'Garanties / Formules',
                'verbose_name_plural': 'Garanties / Formules',
                'db_table': 'garantie_formule',
            },
        ),
    ]
