# Generated by Django 3.2.15 on 2024-11-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0232_carburant_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carosserie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carosseries',
                'verbose_name_plural': 'Carosseries',
                'db_table': 'carosserie',
            },
        ),
    ]
